// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Filter_HW_stream_Filter_vertical_HW_stream (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        output_stream_din,
        output_stream_full_n,
        output_stream_write,
        temp_stream_dout,
        temp_stream_empty_n,
        temp_stream_read
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state7 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output  [7:0] output_stream_din;
input   output_stream_full_n;
output   output_stream_write;
input  [7:0] temp_stream_dout;
input   temp_stream_empty_n;
output   temp_stream_read;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg output_stream_write;
reg temp_stream_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    output_stream_blk_n;
reg    ap_enable_reg_pp0_iter4;
wire    ap_block_pp0_stage0;
reg   [0:0] select_ln219_1_reg_517;
reg   [0:0] select_ln219_1_reg_517_pp0_iter3_reg;
reg    temp_stream_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
reg   [0:0] icmp_ln232_reg_513;
reg   [16:0] indvar_flatten_reg_251;
reg   [8:0] Y_reg_262;
reg   [8:0] X_reg_273;
wire   [16:0] add_ln232_fu_284_p2;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_state2_pp0_stage0_iter0;
reg    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state4_pp0_stage0_iter2;
wire    ap_block_state5_pp0_stage0_iter3;
reg    ap_block_state6_pp0_stage0_iter4;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln232_fu_290_p2;
wire   [0:0] select_ln219_1_fu_328_p3;
reg   [0:0] select_ln219_1_reg_517_pp0_iter1_reg;
reg   [0:0] select_ln219_1_reg_517_pp0_iter2_reg;
wire   [8:0] select_ln219_2_fu_336_p3;
reg   [8:0] select_ln219_2_reg_521;
wire   [2:0] trunc_ln219_fu_344_p1;
reg   [2:0] trunc_ln219_reg_526;
reg   [8:0] temp_0_addr_reg_530;
reg   [8:0] temp_1_addr_1_reg_535;
reg   [8:0] temp_2_addr_1_reg_541;
reg   [8:0] temp_3_addr_1_reg_547;
reg   [8:0] temp_4_addr_1_reg_553;
reg   [8:0] temp_5_addr_1_reg_559;
reg   [8:0] temp_1_addr_reg_565;
reg   [8:0] temp_2_addr_reg_570;
reg   [8:0] temp_3_addr_reg_575;
reg   [8:0] temp_4_addr_reg_580;
reg   [8:0] temp_5_addr_reg_585;
wire   [8:0] add_ln234_fu_363_p2;
reg   [7:0] tmp_reg_595;
reg   [7:0] tmp_reg_595_pp0_iter2_reg;
wire   [7:0] temp_1_q1;
reg   [7:0] temp_1_load_reg_600;
reg   [7:0] temp_1_load_reg_600_pp0_iter2_reg;
wire   [7:0] temp_2_q1;
reg   [7:0] temp_2_load_reg_605;
reg   [7:0] temp_2_load_reg_605_pp0_iter2_reg;
wire   [7:0] temp_4_q1;
reg   [7:0] temp_4_load_reg_615;
reg   [7:0] temp_4_load_reg_615_pp0_iter2_reg;
wire   [7:0] temp_5_q1;
reg   [7:0] temp_5_load_reg_620;
reg   [7:0] temp_5_load_reg_620_pp0_iter2_reg;
wire   [7:0] temp_0_q0;
reg   [7:0] temp_0_load_reg_625;
reg    ap_enable_reg_pp0_iter2;
wire   [8:0] tmp_i_fu_385_p2;
reg   [8:0] tmp_i_reg_630;
wire   [8:0] tmp2_i_fu_391_p2;
reg   [8:0] tmp2_i_reg_636;
reg    ap_block_state1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
reg    ap_enable_reg_pp0_iter3;
reg    temp_0_ce0;
reg    temp_0_we0;
reg   [7:0] temp_0_d0;
reg   [8:0] temp_1_address0;
reg    temp_1_ce0;
reg    temp_1_we0;
reg   [7:0] temp_1_d0;
wire   [8:0] temp_1_address1;
reg    temp_1_ce1;
reg   [8:0] temp_2_address0;
reg    temp_2_ce0;
reg    temp_2_we0;
reg   [7:0] temp_2_d0;
wire   [8:0] temp_2_address1;
reg    temp_2_ce1;
reg   [8:0] temp_3_address0;
reg    temp_3_ce0;
reg    temp_3_we0;
reg   [7:0] temp_3_d0;
wire   [8:0] temp_3_address1;
reg    temp_3_ce1;
wire   [7:0] temp_3_q1;
reg   [8:0] temp_4_address0;
reg    temp_4_ce0;
reg    temp_4_we0;
reg   [7:0] temp_4_d0;
wire   [8:0] temp_4_address1;
reg    temp_4_ce1;
reg   [8:0] temp_5_address0;
reg    temp_5_ce0;
reg    temp_5_we0;
wire   [8:0] temp_5_address1;
reg    temp_5_ce1;
reg   [8:0] ap_phi_mux_Y_phi_fu_266_p4;
wire   [63:0] X_cast_i_fu_348_p1;
reg    ap_block_pp0_stage0_01001;
wire   [0:0] icmp_ln234_fu_296_p2;
wire   [8:0] add_ln232_1_fu_310_p2;
wire   [0:0] cmp2_i_mid1_fu_316_p2;
wire   [0:0] cmp2_i66_fu_322_p2;
wire   [8:0] select_ln219_fu_302_p3;
wire   [8:0] zext_ln240_fu_379_p1;
wire   [8:0] zext_ln246_1_fu_376_p1;
wire   [8:0] zext_ln240_1_fu_382_p1;
wire   [8:0] zext_ln246_fu_373_p1;
wire   [8:0] temp_0_load_cast_i_fu_400_p1;
wire   [8:0] tmp_1_cast_i_fu_397_p1;
wire   [8:0] tmp41_i_fu_403_p2;
wire   [9:0] tmp5_i_fu_409_p3;
wire   [14:0] p_shl3_i_fu_421_p3;
wire   [9:0] p_shl4_i_fu_432_p3;
wire   [15:0] p_shl3_cast_i_fu_428_p1;
wire   [15:0] p_shl4_cast_i_fu_439_p1;
wire   [12:0] p_shl_i_fu_452_p3;
wire   [13:0] p_shl_cast_i_fu_459_p1;
wire   [13:0] tmp2_cast69_i_fu_449_p1;
wire   [13:0] tmp3_i_fu_463_p2;
wire   [14:0] grp_fu_499_p3;
wire   [15:0] zext_ln246_4_fu_473_p1;
wire  signed [15:0] tmp3_cast_i_fu_469_p1;
wire   [15:0] add_ln246_1_fu_476_p2;
wire   [15:0] tmp1_i_fu_443_p2;
wire   [15:0] Sum_fu_482_p2;
wire   [7:0] grp_fu_499_p0;
wire   [7:0] grp_fu_499_p1;
wire   [9:0] grp_fu_499_p2;
reg    grp_fu_499_ce;
wire    ap_CS_fsm_state7;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire   [14:0] grp_fu_499_p00;
wire   [14:0] grp_fu_499_p20;
reg    ap_condition_55;
reg    ap_condition_319;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
end

Filter_HW_stream_Filter_vertical_HW_stream_temp_0 #(
    .DataWidth( 8 ),
    .AddressRange( 474 ),
    .AddressWidth( 9 ))
temp_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(temp_0_addr_reg_530),
    .ce0(temp_0_ce0),
    .we0(temp_0_we0),
    .d0(temp_0_d0),
    .q0(temp_0_q0)
);

Filter_HW_stream_Filter_vertical_HW_stream_temp_1 #(
    .DataWidth( 8 ),
    .AddressRange( 474 ),
    .AddressWidth( 9 ))
temp_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(temp_1_address0),
    .ce0(temp_1_ce0),
    .we0(temp_1_we0),
    .d0(temp_1_d0),
    .address1(temp_1_address1),
    .ce1(temp_1_ce1),
    .q1(temp_1_q1)
);

Filter_HW_stream_Filter_vertical_HW_stream_temp_1 #(
    .DataWidth( 8 ),
    .AddressRange( 474 ),
    .AddressWidth( 9 ))
temp_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(temp_2_address0),
    .ce0(temp_2_ce0),
    .we0(temp_2_we0),
    .d0(temp_2_d0),
    .address1(temp_2_address1),
    .ce1(temp_2_ce1),
    .q1(temp_2_q1)
);

Filter_HW_stream_Filter_vertical_HW_stream_temp_1 #(
    .DataWidth( 8 ),
    .AddressRange( 474 ),
    .AddressWidth( 9 ))
temp_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(temp_3_address0),
    .ce0(temp_3_ce0),
    .we0(temp_3_we0),
    .d0(temp_3_d0),
    .address1(temp_3_address1),
    .ce1(temp_3_ce1),
    .q1(temp_3_q1)
);

Filter_HW_stream_Filter_vertical_HW_stream_temp_1 #(
    .DataWidth( 8 ),
    .AddressRange( 474 ),
    .AddressWidth( 9 ))
temp_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(temp_4_address0),
    .ce0(temp_4_ce0),
    .we0(temp_4_we0),
    .d0(temp_4_d0),
    .address1(temp_4_address1),
    .ce1(temp_4_ce1),
    .q1(temp_4_q1)
);

Filter_HW_stream_Filter_vertical_HW_stream_temp_1 #(
    .DataWidth( 8 ),
    .AddressRange( 474 ),
    .AddressWidth( 9 ))
temp_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(temp_5_address0),
    .ce0(temp_5_ce0),
    .we0(temp_5_we0),
    .d0(temp_stream_dout),
    .address1(temp_5_address1),
    .ce1(temp_5_ce1),
    .q1(temp_5_q1)
);

Filter_HW_stream_mac_muladd_8ns_8ns_10ns_15_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 10 ),
    .dout_WIDTH( 15 ))
mac_muladd_8ns_8ns_10ns_15_4_1_U14(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_499_p0),
    .din1(grp_fu_499_p1),
    .din2(grp_fu_499_p2),
    .ce(grp_fu_499_ce),
    .dout(grp_fu_499_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state7)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state2)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter4 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln232_fu_290_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        X_reg_273 <= add_ln234_fu_363_p2;
    end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        X_reg_273 <= 9'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln232_reg_513 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Y_reg_262 <= select_ln219_2_reg_521;
    end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        Y_reg_262 <= 9'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln232_fu_290_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        indvar_flatten_reg_251 <= add_ln232_fu_284_p2;
    end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten_reg_251 <= 17'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln232_reg_513 <= icmp_ln232_fu_290_p2;
        select_ln219_1_reg_517_pp0_iter1_reg <= select_ln219_1_reg_517;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln232_fu_290_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        select_ln219_1_reg_517 <= select_ln219_1_fu_328_p3;
        temp_0_addr_reg_530 <= X_cast_i_fu_348_p1;
        trunc_ln219_reg_526 <= trunc_ln219_fu_344_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        select_ln219_1_reg_517_pp0_iter2_reg <= select_ln219_1_reg_517_pp0_iter1_reg;
        select_ln219_1_reg_517_pp0_iter3_reg <= select_ln219_1_reg_517_pp0_iter2_reg;
        temp_1_load_reg_600_pp0_iter2_reg <= temp_1_load_reg_600;
        temp_2_load_reg_605_pp0_iter2_reg <= temp_2_load_reg_605;
        temp_4_load_reg_615_pp0_iter2_reg <= temp_4_load_reg_615;
        temp_5_load_reg_620_pp0_iter2_reg <= temp_5_load_reg_620;
        tmp_reg_595_pp0_iter2_reg <= tmp_reg_595;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln232_fu_290_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        select_ln219_2_reg_521 <= select_ln219_2_fu_336_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((select_ln219_1_reg_517_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        temp_0_load_reg_625 <= temp_0_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((select_ln219_1_fu_328_p3 == 1'd0) & (icmp_ln232_fu_290_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        temp_1_addr_1_reg_535 <= X_cast_i_fu_348_p1;
        temp_2_addr_1_reg_541 <= X_cast_i_fu_348_p1;
        temp_3_addr_1_reg_547 <= X_cast_i_fu_348_p1;
        temp_4_addr_1_reg_553 <= X_cast_i_fu_348_p1;
        temp_5_addr_1_reg_559 <= X_cast_i_fu_348_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((select_ln219_1_fu_328_p3 == 1'd1) & (icmp_ln232_fu_290_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        temp_1_addr_reg_565 <= X_cast_i_fu_348_p1;
        temp_2_addr_reg_570 <= X_cast_i_fu_348_p1;
        temp_3_addr_reg_575 <= X_cast_i_fu_348_p1;
        temp_4_addr_reg_580 <= X_cast_i_fu_348_p1;
        temp_5_addr_reg_585 <= X_cast_i_fu_348_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (select_ln219_1_reg_517 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        temp_1_load_reg_600 <= temp_1_q1;
        temp_2_load_reg_605 <= temp_2_q1;
        temp_4_load_reg_615 <= temp_4_q1;
        temp_5_load_reg_620 <= temp_5_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((select_ln219_1_reg_517_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp2_i_reg_636 <= tmp2_i_fu_391_p2;
        tmp_i_reg_630 <= tmp_i_fu_385_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln232_reg_513 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_reg_595 <= temp_stream_dout;
    end
end

always @ (*) begin
    if ((icmp_ln232_fu_290_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln232_reg_513 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_Y_phi_fu_266_p4 = select_ln219_2_reg_521;
    end else begin
        ap_phi_mux_Y_phi_fu_266_p4 = Y_reg_262;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_499_ce = 1'b1;
    end else begin
        grp_fu_499_ce = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln219_1_reg_517_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        output_stream_blk_n = output_stream_full_n;
    end else begin
        output_stream_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((select_ln219_1_reg_517_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        output_stream_write = 1'b1;
    end else begin
        output_stream_write = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (select_ln219_1_reg_517 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln219_reg_526 == 3'd0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (select_ln219_1_reg_517 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        temp_0_ce0 = 1'b1;
    end else begin
        temp_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_55)) begin
        if (((select_ln219_1_reg_517 == 1'd1) & (trunc_ln219_reg_526 == 3'd0))) begin
            temp_0_d0 = temp_stream_dout;
        end else if ((select_ln219_1_reg_517 == 1'd0)) begin
            temp_0_d0 = temp_1_q1;
        end else begin
            temp_0_d0 = 'bx;
        end
    end else begin
        temp_0_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (select_ln219_1_reg_517 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln219_reg_526 == 3'd0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (select_ln219_1_reg_517 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        temp_0_we0 = 1'b1;
    end else begin
        temp_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_55)) begin
        if (((select_ln219_1_reg_517 == 1'd1) & (trunc_ln219_reg_526 == 3'd1))) begin
            temp_1_address0 = temp_1_addr_reg_565;
        end else if ((select_ln219_1_reg_517 == 1'd0)) begin
            temp_1_address0 = temp_1_addr_1_reg_535;
        end else begin
            temp_1_address0 = 'bx;
        end
    end else begin
        temp_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (select_ln219_1_reg_517 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln219_reg_526 == 3'd1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (select_ln219_1_reg_517 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        temp_1_ce0 = 1'b1;
    end else begin
        temp_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        temp_1_ce1 = 1'b1;
    end else begin
        temp_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_55)) begin
        if (((select_ln219_1_reg_517 == 1'd1) & (trunc_ln219_reg_526 == 3'd1))) begin
            temp_1_d0 = temp_stream_dout;
        end else if ((select_ln219_1_reg_517 == 1'd0)) begin
            temp_1_d0 = temp_2_q1;
        end else begin
            temp_1_d0 = 'bx;
        end
    end else begin
        temp_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (select_ln219_1_reg_517 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln219_reg_526 == 3'd1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (select_ln219_1_reg_517 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        temp_1_we0 = 1'b1;
    end else begin
        temp_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_55)) begin
        if (((select_ln219_1_reg_517 == 1'd1) & (trunc_ln219_reg_526 == 3'd2))) begin
            temp_2_address0 = temp_2_addr_reg_570;
        end else if ((select_ln219_1_reg_517 == 1'd0)) begin
            temp_2_address0 = temp_2_addr_1_reg_541;
        end else begin
            temp_2_address0 = 'bx;
        end
    end else begin
        temp_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (select_ln219_1_reg_517 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln219_reg_526 == 3'd2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (select_ln219_1_reg_517 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        temp_2_ce0 = 1'b1;
    end else begin
        temp_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        temp_2_ce1 = 1'b1;
    end else begin
        temp_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_55)) begin
        if (((select_ln219_1_reg_517 == 1'd1) & (trunc_ln219_reg_526 == 3'd2))) begin
            temp_2_d0 = temp_stream_dout;
        end else if ((select_ln219_1_reg_517 == 1'd0)) begin
            temp_2_d0 = temp_3_q1;
        end else begin
            temp_2_d0 = 'bx;
        end
    end else begin
        temp_2_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (select_ln219_1_reg_517 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln219_reg_526 == 3'd2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (select_ln219_1_reg_517 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        temp_2_we0 = 1'b1;
    end else begin
        temp_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_55)) begin
        if (((select_ln219_1_reg_517 == 1'd1) & (trunc_ln219_reg_526 == 3'd3))) begin
            temp_3_address0 = temp_3_addr_reg_575;
        end else if ((select_ln219_1_reg_517 == 1'd0)) begin
            temp_3_address0 = temp_3_addr_1_reg_547;
        end else begin
            temp_3_address0 = 'bx;
        end
    end else begin
        temp_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (select_ln219_1_reg_517 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln219_reg_526 == 3'd3)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (select_ln219_1_reg_517 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        temp_3_ce0 = 1'b1;
    end else begin
        temp_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        temp_3_ce1 = 1'b1;
    end else begin
        temp_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_55)) begin
        if (((select_ln219_1_reg_517 == 1'd1) & (trunc_ln219_reg_526 == 3'd3))) begin
            temp_3_d0 = temp_stream_dout;
        end else if ((select_ln219_1_reg_517 == 1'd0)) begin
            temp_3_d0 = temp_4_q1;
        end else begin
            temp_3_d0 = 'bx;
        end
    end else begin
        temp_3_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (select_ln219_1_reg_517 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln219_reg_526 == 3'd3)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (select_ln219_1_reg_517 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        temp_3_we0 = 1'b1;
    end else begin
        temp_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_55)) begin
        if (((select_ln219_1_reg_517 == 1'd1) & (trunc_ln219_reg_526 == 3'd4))) begin
            temp_4_address0 = temp_4_addr_reg_580;
        end else if ((select_ln219_1_reg_517 == 1'd0)) begin
            temp_4_address0 = temp_4_addr_1_reg_553;
        end else begin
            temp_4_address0 = 'bx;
        end
    end else begin
        temp_4_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (select_ln219_1_reg_517 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln219_reg_526 == 3'd4)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (select_ln219_1_reg_517 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        temp_4_ce0 = 1'b1;
    end else begin
        temp_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        temp_4_ce1 = 1'b1;
    end else begin
        temp_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_55)) begin
        if (((select_ln219_1_reg_517 == 1'd1) & (trunc_ln219_reg_526 == 3'd4))) begin
            temp_4_d0 = temp_stream_dout;
        end else if ((select_ln219_1_reg_517 == 1'd0)) begin
            temp_4_d0 = temp_5_q1;
        end else begin
            temp_4_d0 = 'bx;
        end
    end else begin
        temp_4_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (select_ln219_1_reg_517 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln219_reg_526 == 3'd4)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (select_ln219_1_reg_517 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        temp_4_we0 = 1'b1;
    end else begin
        temp_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_55)) begin
        if ((1'b1 == ap_condition_319)) begin
            temp_5_address0 = temp_5_addr_reg_585;
        end else if ((select_ln219_1_reg_517 == 1'd0)) begin
            temp_5_address0 = temp_5_addr_1_reg_559;
        end else begin
            temp_5_address0 = 'bx;
        end
    end else begin
        temp_5_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (select_ln219_1_reg_517 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | (~(trunc_ln219_reg_526 == 3'd0) & ~(trunc_ln219_reg_526 == 3'd4) & ~(trunc_ln219_reg_526 == 3'd3) & ~(trunc_ln219_reg_526 == 3'd2) & ~(trunc_ln219_reg_526 == 3'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (select_ln219_1_reg_517 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        temp_5_ce0 = 1'b1;
    end else begin
        temp_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        temp_5_ce1 = 1'b1;
    end else begin
        temp_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (select_ln219_1_reg_517 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | (~(trunc_ln219_reg_526 == 3'd0) & ~(trunc_ln219_reg_526 == 3'd4) & ~(trunc_ln219_reg_526 == 3'd3) & ~(trunc_ln219_reg_526 == 3'd2) & ~(trunc_ln219_reg_526 == 3'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (select_ln219_1_reg_517 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        temp_5_we0 = 1'b1;
    end else begin
        temp_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln232_reg_513 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        temp_stream_blk_n = temp_stream_empty_n;
    end else begin
        temp_stream_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln232_reg_513 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        temp_stream_read = 1'b1;
    end else begin
        temp_stream_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((icmp_ln232_fu_290_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone)) & ~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter4 == 1'b1) & (ap_enable_reg_pp0_iter3 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((icmp_ln232_fu_290_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone)) | ((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter4 == 1'b1) & (ap_enable_reg_pp0_iter3 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Sum_fu_482_p2 = (add_ln246_1_fu_476_p2 + tmp1_i_fu_443_p2);

assign X_cast_i_fu_348_p1 = select_ln219_fu_302_p3;

assign add_ln232_1_fu_310_p2 = (ap_phi_mux_Y_phi_fu_266_p4 + 9'd1);

assign add_ln232_fu_284_p2 = (indvar_flatten_reg_251 + 17'd1);

assign add_ln234_fu_363_p2 = (select_ln219_fu_302_p3 + 9'd1);

assign add_ln246_1_fu_476_p2 = ($signed(zext_ln246_4_fu_473_p1) + $signed(tmp3_cast_i_fu_469_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((icmp_ln232_reg_513 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (temp_stream_empty_n == 1'b0)) | ((select_ln219_1_reg_517_pp0_iter3_reg == 1'd0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (output_stream_full_n == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((icmp_ln232_reg_513 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (temp_stream_empty_n == 1'b0)) | ((select_ln219_1_reg_517_pp0_iter3_reg == 1'd0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (output_stream_full_n == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((icmp_ln232_reg_513 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (temp_stream_empty_n == 1'b0)) | ((select_ln219_1_reg_517_pp0_iter3_reg == 1'd0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (output_stream_full_n == 1'b0)));
end

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = ((icmp_ln232_reg_513 == 1'd0) & (temp_stream_empty_n == 1'b0));
end

assign ap_block_state4_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state6_pp0_stage0_iter4 = ((select_ln219_1_reg_517_pp0_iter3_reg == 1'd0) & (output_stream_full_n == 1'b0));
end

always @ (*) begin
    ap_condition_319 = (~(trunc_ln219_reg_526 == 3'd0) & ~(trunc_ln219_reg_526 == 3'd4) & ~(trunc_ln219_reg_526 == 3'd3) & ~(trunc_ln219_reg_526 == 3'd2) & ~(trunc_ln219_reg_526 == 3'd1) & (select_ln219_1_reg_517 == 1'd1));
end

always @ (*) begin
    ap_condition_55 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign cmp2_i66_fu_322_p2 = ((ap_phi_mux_Y_phi_fu_266_p4 < 9'd6) ? 1'b1 : 1'b0);

assign cmp2_i_mid1_fu_316_p2 = ((add_ln232_1_fu_310_p2 < 9'd6) ? 1'b1 : 1'b0);

assign grp_fu_499_p0 = grp_fu_499_p00;

assign grp_fu_499_p00 = temp_3_q1;

assign grp_fu_499_p1 = 15'd98;

assign grp_fu_499_p2 = grp_fu_499_p20;

assign grp_fu_499_p20 = tmp5_i_fu_409_p3;

assign icmp_ln232_fu_290_p2 = ((indvar_flatten_reg_251 == 17'd127980) ? 1'b1 : 1'b0);

assign icmp_ln234_fu_296_p2 = ((X_reg_273 == 9'd474) ? 1'b1 : 1'b0);

assign output_stream_din = {{Sum_fu_482_p2[15:8]}};

assign p_shl3_cast_i_fu_428_p1 = p_shl3_i_fu_421_p3;

assign p_shl3_i_fu_421_p3 = {{tmp_i_reg_630}, {6'd0}};

assign p_shl4_cast_i_fu_439_p1 = p_shl4_i_fu_432_p3;

assign p_shl4_i_fu_432_p3 = {{tmp_i_reg_630}, {1'd0}};

assign p_shl_cast_i_fu_459_p1 = p_shl_i_fu_452_p3;

assign p_shl_i_fu_452_p3 = {{tmp2_i_reg_636}, {4'd0}};

assign select_ln219_1_fu_328_p3 = ((icmp_ln234_fu_296_p2[0:0] == 1'b1) ? cmp2_i_mid1_fu_316_p2 : cmp2_i66_fu_322_p2);

assign select_ln219_2_fu_336_p3 = ((icmp_ln234_fu_296_p2[0:0] == 1'b1) ? add_ln232_1_fu_310_p2 : ap_phi_mux_Y_phi_fu_266_p4);

assign select_ln219_fu_302_p3 = ((icmp_ln234_fu_296_p2[0:0] == 1'b1) ? 9'd0 : X_reg_273);

assign temp_0_load_cast_i_fu_400_p1 = temp_0_load_reg_625;

assign temp_1_address1 = X_cast_i_fu_348_p1;

assign temp_2_address1 = X_cast_i_fu_348_p1;

assign temp_3_address1 = X_cast_i_fu_348_p1;

assign temp_4_address1 = X_cast_i_fu_348_p1;

assign temp_5_address1 = X_cast_i_fu_348_p1;

assign tmp1_i_fu_443_p2 = (p_shl3_cast_i_fu_428_p1 - p_shl4_cast_i_fu_439_p1);

assign tmp2_cast69_i_fu_449_p1 = tmp2_i_reg_636;

assign tmp2_i_fu_391_p2 = (zext_ln240_1_fu_382_p1 + zext_ln246_fu_373_p1);

assign tmp3_cast_i_fu_469_p1 = $signed(tmp3_i_fu_463_p2);

assign tmp3_i_fu_463_p2 = (p_shl_cast_i_fu_459_p1 - tmp2_cast69_i_fu_449_p1);

assign tmp41_i_fu_403_p2 = (temp_0_load_cast_i_fu_400_p1 + tmp_1_cast_i_fu_397_p1);

assign tmp5_i_fu_409_p3 = {{tmp41_i_fu_403_p2}, {1'd0}};

assign tmp_1_cast_i_fu_397_p1 = tmp_reg_595_pp0_iter2_reg;

assign tmp_i_fu_385_p2 = (zext_ln240_fu_379_p1 + zext_ln246_1_fu_376_p1);

assign trunc_ln219_fu_344_p1 = select_ln219_2_fu_336_p3[2:0];

assign zext_ln240_1_fu_382_p1 = temp_5_load_reg_620_pp0_iter2_reg;

assign zext_ln240_fu_379_p1 = temp_4_load_reg_615_pp0_iter2_reg;

assign zext_ln246_1_fu_376_p1 = temp_2_load_reg_605_pp0_iter2_reg;

assign zext_ln246_4_fu_473_p1 = grp_fu_499_p3;

assign zext_ln246_fu_373_p1 = temp_1_load_reg_600_pp0_iter2_reg;

endmodule //Filter_HW_stream_Filter_vertical_HW_stream
