#ifndef SRC_CONSTANTS_
#define SRC_CONSTANTS_

#define INPUT_HEIGHT_SCALE (540)
#define INPUT_WIDTH_SCALE (960)
#define FRAME_SIZE (INPUT_WIDTH_SCALE * INPUT_HEIGHT_SCALE)
#define FRAMES (200)
#define MAX_OUTPUT_SIZE (5000 * 1024 * 10)
#define INPUT_FILTER_HEIGHT (270)
#define INPUT_FILTER_WIDTH (480)
#define OUTPUT_FILTER_WIDTH (474)
#define INPUT_DIFF_HEIGHT (INPUT_FILTER_HEIGHT - (7 - 1))
#define INPUT_DIFF_WIDTH (INPUT_FILTER_WIDTH - (7 - 1))
#define INPUT_COMP_HEIGHT (264)
#define INPUT_COMP_WIDTH  (474)
#define INPUT_COMPRESS_SIZE (264 * 474)
#endif