// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="encoding_encoding,hls_ip_2020_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu3eg-sbva484-1-i,HLS_INPUT_CLOCK=6.670000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=4.869100,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=311,HLS_SYN_DSP=0,HLS_SYN_FF=5395,HLS_SYN_LUT=14501,HLS_VERSION=2020_2}" *)

module encoding (
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        ap_clk,
        ap_rst_n,
        interrupt,
        m_axi_p0_AWVALID,
        m_axi_p0_AWREADY,
        m_axi_p0_AWADDR,
        m_axi_p0_AWID,
        m_axi_p0_AWLEN,
        m_axi_p0_AWSIZE,
        m_axi_p0_AWBURST,
        m_axi_p0_AWLOCK,
        m_axi_p0_AWCACHE,
        m_axi_p0_AWPROT,
        m_axi_p0_AWQOS,
        m_axi_p0_AWREGION,
        m_axi_p0_AWUSER,
        m_axi_p0_WVALID,
        m_axi_p0_WREADY,
        m_axi_p0_WDATA,
        m_axi_p0_WSTRB,
        m_axi_p0_WLAST,
        m_axi_p0_WID,
        m_axi_p0_WUSER,
        m_axi_p0_ARVALID,
        m_axi_p0_ARREADY,
        m_axi_p0_ARADDR,
        m_axi_p0_ARID,
        m_axi_p0_ARLEN,
        m_axi_p0_ARSIZE,
        m_axi_p0_ARBURST,
        m_axi_p0_ARLOCK,
        m_axi_p0_ARCACHE,
        m_axi_p0_ARPROT,
        m_axi_p0_ARQOS,
        m_axi_p0_ARREGION,
        m_axi_p0_ARUSER,
        m_axi_p0_RVALID,
        m_axi_p0_RREADY,
        m_axi_p0_RDATA,
        m_axi_p0_RLAST,
        m_axi_p0_RID,
        m_axi_p0_RUSER,
        m_axi_p0_RRESP,
        m_axi_p0_BVALID,
        m_axi_p0_BREADY,
        m_axi_p0_BRESP,
        m_axi_p0_BID,
        m_axi_p0_BUSER,
        m_axi_p1_AWVALID,
        m_axi_p1_AWREADY,
        m_axi_p1_AWADDR,
        m_axi_p1_AWID,
        m_axi_p1_AWLEN,
        m_axi_p1_AWSIZE,
        m_axi_p1_AWBURST,
        m_axi_p1_AWLOCK,
        m_axi_p1_AWCACHE,
        m_axi_p1_AWPROT,
        m_axi_p1_AWQOS,
        m_axi_p1_AWREGION,
        m_axi_p1_AWUSER,
        m_axi_p1_WVALID,
        m_axi_p1_WREADY,
        m_axi_p1_WDATA,
        m_axi_p1_WSTRB,
        m_axi_p1_WLAST,
        m_axi_p1_WID,
        m_axi_p1_WUSER,
        m_axi_p1_ARVALID,
        m_axi_p1_ARREADY,
        m_axi_p1_ARADDR,
        m_axi_p1_ARID,
        m_axi_p1_ARLEN,
        m_axi_p1_ARSIZE,
        m_axi_p1_ARBURST,
        m_axi_p1_ARLOCK,
        m_axi_p1_ARCACHE,
        m_axi_p1_ARPROT,
        m_axi_p1_ARQOS,
        m_axi_p1_ARREGION,
        m_axi_p1_ARUSER,
        m_axi_p1_RVALID,
        m_axi_p1_RREADY,
        m_axi_p1_RDATA,
        m_axi_p1_RLAST,
        m_axi_p1_RID,
        m_axi_p1_RUSER,
        m_axi_p1_RRESP,
        m_axi_p1_BVALID,
        m_axi_p1_BREADY,
        m_axi_p1_BRESP,
        m_axi_p1_BID,
        m_axi_p1_BUSER,
        m_axi_p2_AWVALID,
        m_axi_p2_AWREADY,
        m_axi_p2_AWADDR,
        m_axi_p2_AWID,
        m_axi_p2_AWLEN,
        m_axi_p2_AWSIZE,
        m_axi_p2_AWBURST,
        m_axi_p2_AWLOCK,
        m_axi_p2_AWCACHE,
        m_axi_p2_AWPROT,
        m_axi_p2_AWQOS,
        m_axi_p2_AWREGION,
        m_axi_p2_AWUSER,
        m_axi_p2_WVALID,
        m_axi_p2_WREADY,
        m_axi_p2_WDATA,
        m_axi_p2_WSTRB,
        m_axi_p2_WLAST,
        m_axi_p2_WID,
        m_axi_p2_WUSER,
        m_axi_p2_ARVALID,
        m_axi_p2_ARREADY,
        m_axi_p2_ARADDR,
        m_axi_p2_ARID,
        m_axi_p2_ARLEN,
        m_axi_p2_ARSIZE,
        m_axi_p2_ARBURST,
        m_axi_p2_ARLOCK,
        m_axi_p2_ARCACHE,
        m_axi_p2_ARPROT,
        m_axi_p2_ARQOS,
        m_axi_p2_ARREGION,
        m_axi_p2_ARUSER,
        m_axi_p2_RVALID,
        m_axi_p2_RREADY,
        m_axi_p2_RDATA,
        m_axi_p2_RLAST,
        m_axi_p2_RID,
        m_axi_p2_RUSER,
        m_axi_p2_RRESP,
        m_axi_p2_BVALID,
        m_axi_p2_BREADY,
        m_axi_p2_BRESP,
        m_axi_p2_BID,
        m_axi_p2_BUSER,
        m_axi_p3_AWVALID,
        m_axi_p3_AWREADY,
        m_axi_p3_AWADDR,
        m_axi_p3_AWID,
        m_axi_p3_AWLEN,
        m_axi_p3_AWSIZE,
        m_axi_p3_AWBURST,
        m_axi_p3_AWLOCK,
        m_axi_p3_AWCACHE,
        m_axi_p3_AWPROT,
        m_axi_p3_AWQOS,
        m_axi_p3_AWREGION,
        m_axi_p3_AWUSER,
        m_axi_p3_WVALID,
        m_axi_p3_WREADY,
        m_axi_p3_WDATA,
        m_axi_p3_WSTRB,
        m_axi_p3_WLAST,
        m_axi_p3_WID,
        m_axi_p3_WUSER,
        m_axi_p3_ARVALID,
        m_axi_p3_ARREADY,
        m_axi_p3_ARADDR,
        m_axi_p3_ARID,
        m_axi_p3_ARLEN,
        m_axi_p3_ARSIZE,
        m_axi_p3_ARBURST,
        m_axi_p3_ARLOCK,
        m_axi_p3_ARCACHE,
        m_axi_p3_ARPROT,
        m_axi_p3_ARQOS,
        m_axi_p3_ARREGION,
        m_axi_p3_ARUSER,
        m_axi_p3_RVALID,
        m_axi_p3_RREADY,
        m_axi_p3_RDATA,
        m_axi_p3_RLAST,
        m_axi_p3_RID,
        m_axi_p3_RUSER,
        m_axi_p3_RRESP,
        m_axi_p3_BVALID,
        m_axi_p3_BREADY,
        m_axi_p3_BRESP,
        m_axi_p3_BID,
        m_axi_p3_BUSER
);

parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_S_AXI_ADDR_WIDTH = 32;
parameter    C_M_AXI_P0_ID_WIDTH = 1;
parameter    C_M_AXI_P0_ADDR_WIDTH = 64;
parameter    C_M_AXI_P0_DATA_WIDTH = 32;
parameter    C_M_AXI_P0_AWUSER_WIDTH = 1;
parameter    C_M_AXI_P0_ARUSER_WIDTH = 1;
parameter    C_M_AXI_P0_WUSER_WIDTH = 1;
parameter    C_M_AXI_P0_RUSER_WIDTH = 1;
parameter    C_M_AXI_P0_BUSER_WIDTH = 1;
parameter    C_M_AXI_P0_USER_VALUE = 0;
parameter    C_M_AXI_P0_PROT_VALUE = 0;
parameter    C_M_AXI_P0_CACHE_VALUE = 3;
parameter    C_M_AXI_ID_WIDTH = 1;
parameter    C_M_AXI_ADDR_WIDTH = 64;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_AWUSER_WIDTH = 1;
parameter    C_M_AXI_ARUSER_WIDTH = 1;
parameter    C_M_AXI_WUSER_WIDTH = 1;
parameter    C_M_AXI_RUSER_WIDTH = 1;
parameter    C_M_AXI_BUSER_WIDTH = 1;
parameter    C_M_AXI_P1_ID_WIDTH = 1;
parameter    C_M_AXI_P1_ADDR_WIDTH = 64;
parameter    C_M_AXI_P1_DATA_WIDTH = 32;
parameter    C_M_AXI_P1_AWUSER_WIDTH = 1;
parameter    C_M_AXI_P1_ARUSER_WIDTH = 1;
parameter    C_M_AXI_P1_WUSER_WIDTH = 1;
parameter    C_M_AXI_P1_RUSER_WIDTH = 1;
parameter    C_M_AXI_P1_BUSER_WIDTH = 1;
parameter    C_M_AXI_P1_USER_VALUE = 0;
parameter    C_M_AXI_P1_PROT_VALUE = 0;
parameter    C_M_AXI_P1_CACHE_VALUE = 3;
parameter    C_M_AXI_P2_ID_WIDTH = 1;
parameter    C_M_AXI_P2_ADDR_WIDTH = 64;
parameter    C_M_AXI_P2_DATA_WIDTH = 32;
parameter    C_M_AXI_P2_AWUSER_WIDTH = 1;
parameter    C_M_AXI_P2_ARUSER_WIDTH = 1;
parameter    C_M_AXI_P2_WUSER_WIDTH = 1;
parameter    C_M_AXI_P2_RUSER_WIDTH = 1;
parameter    C_M_AXI_P2_BUSER_WIDTH = 1;
parameter    C_M_AXI_P2_USER_VALUE = 0;
parameter    C_M_AXI_P2_PROT_VALUE = 0;
parameter    C_M_AXI_P2_CACHE_VALUE = 3;
parameter    C_M_AXI_P3_ID_WIDTH = 1;
parameter    C_M_AXI_P3_ADDR_WIDTH = 64;
parameter    C_M_AXI_P3_DATA_WIDTH = 32;
parameter    C_M_AXI_P3_AWUSER_WIDTH = 1;
parameter    C_M_AXI_P3_ARUSER_WIDTH = 1;
parameter    C_M_AXI_P3_WUSER_WIDTH = 1;
parameter    C_M_AXI_P3_RUSER_WIDTH = 1;
parameter    C_M_AXI_P3_BUSER_WIDTH = 1;
parameter    C_M_AXI_P3_USER_VALUE = 0;
parameter    C_M_AXI_P3_PROT_VALUE = 0;
parameter    C_M_AXI_P3_CACHE_VALUE = 3;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_P0_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_P1_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_P2_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_P3_WSTRB_WIDTH = (32 / 8);

input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
input   ap_clk;
input   ap_rst_n;
output   interrupt;
output   m_axi_p0_AWVALID;
input   m_axi_p0_AWREADY;
output  [C_M_AXI_P0_ADDR_WIDTH - 1:0] m_axi_p0_AWADDR;
output  [C_M_AXI_P0_ID_WIDTH - 1:0] m_axi_p0_AWID;
output  [7:0] m_axi_p0_AWLEN;
output  [2:0] m_axi_p0_AWSIZE;
output  [1:0] m_axi_p0_AWBURST;
output  [1:0] m_axi_p0_AWLOCK;
output  [3:0] m_axi_p0_AWCACHE;
output  [2:0] m_axi_p0_AWPROT;
output  [3:0] m_axi_p0_AWQOS;
output  [3:0] m_axi_p0_AWREGION;
output  [C_M_AXI_P0_AWUSER_WIDTH - 1:0] m_axi_p0_AWUSER;
output   m_axi_p0_WVALID;
input   m_axi_p0_WREADY;
output  [C_M_AXI_P0_DATA_WIDTH - 1:0] m_axi_p0_WDATA;
output  [C_M_AXI_P0_WSTRB_WIDTH - 1:0] m_axi_p0_WSTRB;
output   m_axi_p0_WLAST;
output  [C_M_AXI_P0_ID_WIDTH - 1:0] m_axi_p0_WID;
output  [C_M_AXI_P0_WUSER_WIDTH - 1:0] m_axi_p0_WUSER;
output   m_axi_p0_ARVALID;
input   m_axi_p0_ARREADY;
output  [C_M_AXI_P0_ADDR_WIDTH - 1:0] m_axi_p0_ARADDR;
output  [C_M_AXI_P0_ID_WIDTH - 1:0] m_axi_p0_ARID;
output  [7:0] m_axi_p0_ARLEN;
output  [2:0] m_axi_p0_ARSIZE;
output  [1:0] m_axi_p0_ARBURST;
output  [1:0] m_axi_p0_ARLOCK;
output  [3:0] m_axi_p0_ARCACHE;
output  [2:0] m_axi_p0_ARPROT;
output  [3:0] m_axi_p0_ARQOS;
output  [3:0] m_axi_p0_ARREGION;
output  [C_M_AXI_P0_ARUSER_WIDTH - 1:0] m_axi_p0_ARUSER;
input   m_axi_p0_RVALID;
output   m_axi_p0_RREADY;
input  [C_M_AXI_P0_DATA_WIDTH - 1:0] m_axi_p0_RDATA;
input   m_axi_p0_RLAST;
input  [C_M_AXI_P0_ID_WIDTH - 1:0] m_axi_p0_RID;
input  [C_M_AXI_P0_RUSER_WIDTH - 1:0] m_axi_p0_RUSER;
input  [1:0] m_axi_p0_RRESP;
input   m_axi_p0_BVALID;
output   m_axi_p0_BREADY;
input  [1:0] m_axi_p0_BRESP;
input  [C_M_AXI_P0_ID_WIDTH - 1:0] m_axi_p0_BID;
input  [C_M_AXI_P0_BUSER_WIDTH - 1:0] m_axi_p0_BUSER;
output   m_axi_p1_AWVALID;
input   m_axi_p1_AWREADY;
output  [C_M_AXI_P1_ADDR_WIDTH - 1:0] m_axi_p1_AWADDR;
output  [C_M_AXI_P1_ID_WIDTH - 1:0] m_axi_p1_AWID;
output  [7:0] m_axi_p1_AWLEN;
output  [2:0] m_axi_p1_AWSIZE;
output  [1:0] m_axi_p1_AWBURST;
output  [1:0] m_axi_p1_AWLOCK;
output  [3:0] m_axi_p1_AWCACHE;
output  [2:0] m_axi_p1_AWPROT;
output  [3:0] m_axi_p1_AWQOS;
output  [3:0] m_axi_p1_AWREGION;
output  [C_M_AXI_P1_AWUSER_WIDTH - 1:0] m_axi_p1_AWUSER;
output   m_axi_p1_WVALID;
input   m_axi_p1_WREADY;
output  [C_M_AXI_P1_DATA_WIDTH - 1:0] m_axi_p1_WDATA;
output  [C_M_AXI_P1_WSTRB_WIDTH - 1:0] m_axi_p1_WSTRB;
output   m_axi_p1_WLAST;
output  [C_M_AXI_P1_ID_WIDTH - 1:0] m_axi_p1_WID;
output  [C_M_AXI_P1_WUSER_WIDTH - 1:0] m_axi_p1_WUSER;
output   m_axi_p1_ARVALID;
input   m_axi_p1_ARREADY;
output  [C_M_AXI_P1_ADDR_WIDTH - 1:0] m_axi_p1_ARADDR;
output  [C_M_AXI_P1_ID_WIDTH - 1:0] m_axi_p1_ARID;
output  [7:0] m_axi_p1_ARLEN;
output  [2:0] m_axi_p1_ARSIZE;
output  [1:0] m_axi_p1_ARBURST;
output  [1:0] m_axi_p1_ARLOCK;
output  [3:0] m_axi_p1_ARCACHE;
output  [2:0] m_axi_p1_ARPROT;
output  [3:0] m_axi_p1_ARQOS;
output  [3:0] m_axi_p1_ARREGION;
output  [C_M_AXI_P1_ARUSER_WIDTH - 1:0] m_axi_p1_ARUSER;
input   m_axi_p1_RVALID;
output   m_axi_p1_RREADY;
input  [C_M_AXI_P1_DATA_WIDTH - 1:0] m_axi_p1_RDATA;
input   m_axi_p1_RLAST;
input  [C_M_AXI_P1_ID_WIDTH - 1:0] m_axi_p1_RID;
input  [C_M_AXI_P1_RUSER_WIDTH - 1:0] m_axi_p1_RUSER;
input  [1:0] m_axi_p1_RRESP;
input   m_axi_p1_BVALID;
output   m_axi_p1_BREADY;
input  [1:0] m_axi_p1_BRESP;
input  [C_M_AXI_P1_ID_WIDTH - 1:0] m_axi_p1_BID;
input  [C_M_AXI_P1_BUSER_WIDTH - 1:0] m_axi_p1_BUSER;
output   m_axi_p2_AWVALID;
input   m_axi_p2_AWREADY;
output  [C_M_AXI_P2_ADDR_WIDTH - 1:0] m_axi_p2_AWADDR;
output  [C_M_AXI_P2_ID_WIDTH - 1:0] m_axi_p2_AWID;
output  [7:0] m_axi_p2_AWLEN;
output  [2:0] m_axi_p2_AWSIZE;
output  [1:0] m_axi_p2_AWBURST;
output  [1:0] m_axi_p2_AWLOCK;
output  [3:0] m_axi_p2_AWCACHE;
output  [2:0] m_axi_p2_AWPROT;
output  [3:0] m_axi_p2_AWQOS;
output  [3:0] m_axi_p2_AWREGION;
output  [C_M_AXI_P2_AWUSER_WIDTH - 1:0] m_axi_p2_AWUSER;
output   m_axi_p2_WVALID;
input   m_axi_p2_WREADY;
output  [C_M_AXI_P2_DATA_WIDTH - 1:0] m_axi_p2_WDATA;
output  [C_M_AXI_P2_WSTRB_WIDTH - 1:0] m_axi_p2_WSTRB;
output   m_axi_p2_WLAST;
output  [C_M_AXI_P2_ID_WIDTH - 1:0] m_axi_p2_WID;
output  [C_M_AXI_P2_WUSER_WIDTH - 1:0] m_axi_p2_WUSER;
output   m_axi_p2_ARVALID;
input   m_axi_p2_ARREADY;
output  [C_M_AXI_P2_ADDR_WIDTH - 1:0] m_axi_p2_ARADDR;
output  [C_M_AXI_P2_ID_WIDTH - 1:0] m_axi_p2_ARID;
output  [7:0] m_axi_p2_ARLEN;
output  [2:0] m_axi_p2_ARSIZE;
output  [1:0] m_axi_p2_ARBURST;
output  [1:0] m_axi_p2_ARLOCK;
output  [3:0] m_axi_p2_ARCACHE;
output  [2:0] m_axi_p2_ARPROT;
output  [3:0] m_axi_p2_ARQOS;
output  [3:0] m_axi_p2_ARREGION;
output  [C_M_AXI_P2_ARUSER_WIDTH - 1:0] m_axi_p2_ARUSER;
input   m_axi_p2_RVALID;
output   m_axi_p2_RREADY;
input  [C_M_AXI_P2_DATA_WIDTH - 1:0] m_axi_p2_RDATA;
input   m_axi_p2_RLAST;
input  [C_M_AXI_P2_ID_WIDTH - 1:0] m_axi_p2_RID;
input  [C_M_AXI_P2_RUSER_WIDTH - 1:0] m_axi_p2_RUSER;
input  [1:0] m_axi_p2_RRESP;
input   m_axi_p2_BVALID;
output   m_axi_p2_BREADY;
input  [1:0] m_axi_p2_BRESP;
input  [C_M_AXI_P2_ID_WIDTH - 1:0] m_axi_p2_BID;
input  [C_M_AXI_P2_BUSER_WIDTH - 1:0] m_axi_p2_BUSER;
output   m_axi_p3_AWVALID;
input   m_axi_p3_AWREADY;
output  [C_M_AXI_P3_ADDR_WIDTH - 1:0] m_axi_p3_AWADDR;
output  [C_M_AXI_P3_ID_WIDTH - 1:0] m_axi_p3_AWID;
output  [7:0] m_axi_p3_AWLEN;
output  [2:0] m_axi_p3_AWSIZE;
output  [1:0] m_axi_p3_AWBURST;
output  [1:0] m_axi_p3_AWLOCK;
output  [3:0] m_axi_p3_AWCACHE;
output  [2:0] m_axi_p3_AWPROT;
output  [3:0] m_axi_p3_AWQOS;
output  [3:0] m_axi_p3_AWREGION;
output  [C_M_AXI_P3_AWUSER_WIDTH - 1:0] m_axi_p3_AWUSER;
output   m_axi_p3_WVALID;
input   m_axi_p3_WREADY;
output  [C_M_AXI_P3_DATA_WIDTH - 1:0] m_axi_p3_WDATA;
output  [C_M_AXI_P3_WSTRB_WIDTH - 1:0] m_axi_p3_WSTRB;
output   m_axi_p3_WLAST;
output  [C_M_AXI_P3_ID_WIDTH - 1:0] m_axi_p3_WID;
output  [C_M_AXI_P3_WUSER_WIDTH - 1:0] m_axi_p3_WUSER;
output   m_axi_p3_ARVALID;
input   m_axi_p3_ARREADY;
output  [C_M_AXI_P3_ADDR_WIDTH - 1:0] m_axi_p3_ARADDR;
output  [C_M_AXI_P3_ID_WIDTH - 1:0] m_axi_p3_ARID;
output  [7:0] m_axi_p3_ARLEN;
output  [2:0] m_axi_p3_ARSIZE;
output  [1:0] m_axi_p3_ARBURST;
output  [1:0] m_axi_p3_ARLOCK;
output  [3:0] m_axi_p3_ARCACHE;
output  [2:0] m_axi_p3_ARPROT;
output  [3:0] m_axi_p3_ARQOS;
output  [3:0] m_axi_p3_ARREGION;
output  [C_M_AXI_P3_ARUSER_WIDTH - 1:0] m_axi_p3_ARUSER;
input   m_axi_p3_RVALID;
output   m_axi_p3_RREADY;
input  [C_M_AXI_P3_DATA_WIDTH - 1:0] m_axi_p3_RDATA;
input   m_axi_p3_RLAST;
input  [C_M_AXI_P3_ID_WIDTH - 1:0] m_axi_p3_RID;
input  [C_M_AXI_P3_RUSER_WIDTH - 1:0] m_axi_p3_RUSER;
input  [1:0] m_axi_p3_RRESP;
input   m_axi_p3_BVALID;
output   m_axi_p3_BREADY;
input  [1:0] m_axi_p3_BRESP;
input  [C_M_AXI_P3_ID_WIDTH - 1:0] m_axi_p3_BID;
input  [C_M_AXI_P3_BUSER_WIDTH - 1:0] m_axi_p3_BUSER;

(* shreg_extract = "no" *) reg    ap_rst_reg_2;
(* shreg_extract = "no" *) reg    ap_rst_reg_1;
(* shreg_extract = "no" *) reg    ap_rst_n_inv;
wire   [63:0] buff;
wire   [63:0] input_length;
wire   [63:0] output_compress;
wire   [63:0] output_length;
wire    ap_start;
wire    ap_ready;
wire    ap_done;
wire    ap_continue;
wire    ap_idle;
wire    p0_AWREADY;
wire    p0_WREADY;
wire    p0_ARREADY;
wire    p0_RVALID;
wire   [7:0] p0_RDATA;
wire    p0_RLAST;
wire   [0:0] p0_RID;
wire   [0:0] p0_RUSER;
wire   [1:0] p0_RRESP;
wire    p0_BVALID;
wire   [1:0] p0_BRESP;
wire   [0:0] p0_BID;
wire   [0:0] p0_BUSER;
wire    p1_AWREADY;
wire    p1_WREADY;
wire    p1_ARREADY;
wire    p1_RVALID;
wire   [31:0] p1_RDATA;
wire    p1_RLAST;
wire   [0:0] p1_RID;
wire   [0:0] p1_RUSER;
wire   [1:0] p1_RRESP;
wire    p1_BVALID;
wire   [1:0] p1_BRESP;
wire   [0:0] p1_BID;
wire   [0:0] p1_BUSER;
wire    p2_AWREADY;
wire    p2_WREADY;
wire    p2_ARREADY;
wire    p2_RVALID;
wire   [15:0] p2_RDATA;
wire    p2_RLAST;
wire   [0:0] p2_RID;
wire   [0:0] p2_RUSER;
wire   [1:0] p2_RRESP;
wire    p2_BVALID;
wire   [1:0] p2_BRESP;
wire   [0:0] p2_BID;
wire   [0:0] p2_BUSER;
wire    p3_AWREADY;
wire    p3_WREADY;
wire    p3_ARREADY;
wire    p3_RVALID;
wire   [31:0] p3_RDATA;
wire    p3_RLAST;
wire   [0:0] p3_RID;
wire   [0:0] p3_RUSER;
wire   [1:0] p3_RRESP;
wire    p3_BVALID;
wire   [1:0] p3_BRESP;
wire   [0:0] p3_BID;
wire   [0:0] p3_BUSER;
wire    load6_U0_ap_start;
wire    load6_U0_start_full_n;
wire    load6_U0_ap_done;
wire    load6_U0_ap_continue;
wire    load6_U0_ap_idle;
wire    load6_U0_ap_ready;
wire    load6_U0_start_out;
wire    load6_U0_start_write;
wire    load6_U0_m_axi_p0_AWVALID;
wire   [63:0] load6_U0_m_axi_p0_AWADDR;
wire   [0:0] load6_U0_m_axi_p0_AWID;
wire   [31:0] load6_U0_m_axi_p0_AWLEN;
wire   [2:0] load6_U0_m_axi_p0_AWSIZE;
wire   [1:0] load6_U0_m_axi_p0_AWBURST;
wire   [1:0] load6_U0_m_axi_p0_AWLOCK;
wire   [3:0] load6_U0_m_axi_p0_AWCACHE;
wire   [2:0] load6_U0_m_axi_p0_AWPROT;
wire   [3:0] load6_U0_m_axi_p0_AWQOS;
wire   [3:0] load6_U0_m_axi_p0_AWREGION;
wire   [0:0] load6_U0_m_axi_p0_AWUSER;
wire    load6_U0_m_axi_p0_WVALID;
wire   [7:0] load6_U0_m_axi_p0_WDATA;
wire   [0:0] load6_U0_m_axi_p0_WSTRB;
wire    load6_U0_m_axi_p0_WLAST;
wire   [0:0] load6_U0_m_axi_p0_WID;
wire   [0:0] load6_U0_m_axi_p0_WUSER;
wire    load6_U0_m_axi_p0_ARVALID;
wire   [63:0] load6_U0_m_axi_p0_ARADDR;
wire   [0:0] load6_U0_m_axi_p0_ARID;
wire   [31:0] load6_U0_m_axi_p0_ARLEN;
wire   [2:0] load6_U0_m_axi_p0_ARSIZE;
wire   [1:0] load6_U0_m_axi_p0_ARBURST;
wire   [1:0] load6_U0_m_axi_p0_ARLOCK;
wire   [3:0] load6_U0_m_axi_p0_ARCACHE;
wire   [2:0] load6_U0_m_axi_p0_ARPROT;
wire   [3:0] load6_U0_m_axi_p0_ARQOS;
wire   [3:0] load6_U0_m_axi_p0_ARREGION;
wire   [0:0] load6_U0_m_axi_p0_ARUSER;
wire    load6_U0_m_axi_p0_RREADY;
wire    load6_U0_m_axi_p0_BREADY;
wire   [7:0] load6_U0_instream_din;
wire    load6_U0_instream_write;
wire    load6_U0_m_axi_p1_AWVALID;
wire   [63:0] load6_U0_m_axi_p1_AWADDR;
wire   [0:0] load6_U0_m_axi_p1_AWID;
wire   [31:0] load6_U0_m_axi_p1_AWLEN;
wire   [2:0] load6_U0_m_axi_p1_AWSIZE;
wire   [1:0] load6_U0_m_axi_p1_AWBURST;
wire   [1:0] load6_U0_m_axi_p1_AWLOCK;
wire   [3:0] load6_U0_m_axi_p1_AWCACHE;
wire   [2:0] load6_U0_m_axi_p1_AWPROT;
wire   [3:0] load6_U0_m_axi_p1_AWQOS;
wire   [3:0] load6_U0_m_axi_p1_AWREGION;
wire   [0:0] load6_U0_m_axi_p1_AWUSER;
wire    load6_U0_m_axi_p1_WVALID;
wire   [31:0] load6_U0_m_axi_p1_WDATA;
wire   [3:0] load6_U0_m_axi_p1_WSTRB;
wire    load6_U0_m_axi_p1_WLAST;
wire   [0:0] load6_U0_m_axi_p1_WID;
wire   [0:0] load6_U0_m_axi_p1_WUSER;
wire    load6_U0_m_axi_p1_ARVALID;
wire   [63:0] load6_U0_m_axi_p1_ARADDR;
wire   [0:0] load6_U0_m_axi_p1_ARID;
wire   [31:0] load6_U0_m_axi_p1_ARLEN;
wire   [2:0] load6_U0_m_axi_p1_ARSIZE;
wire   [1:0] load6_U0_m_axi_p1_ARBURST;
wire   [1:0] load6_U0_m_axi_p1_ARLOCK;
wire   [3:0] load6_U0_m_axi_p1_ARCACHE;
wire   [2:0] load6_U0_m_axi_p1_ARPROT;
wire   [3:0] load6_U0_m_axi_p1_ARQOS;
wire   [3:0] load6_U0_m_axi_p1_ARREGION;
wire   [0:0] load6_U0_m_axi_p1_ARUSER;
wire    load6_U0_m_axi_p1_RREADY;
wire    load6_U0_m_axi_p1_BREADY;
wire   [31:0] load6_U0_inlen_stream_din;
wire    load6_U0_inlen_stream_write;
wire   [63:0] load6_U0_output_compress_out_din;
wire    load6_U0_output_compress_out_write;
wire   [63:0] load6_U0_output_length_out_din;
wire    load6_U0_output_length_out_write;
wire    lzw_compute_U0_ap_start;
wire    lzw_compute_U0_ap_done;
wire    lzw_compute_U0_ap_continue;
wire    lzw_compute_U0_ap_idle;
wire    lzw_compute_U0_ap_ready;
wire    lzw_compute_U0_instream_read;
wire    lzw_compute_U0_inlen_stream_read;
wire   [15:0] lzw_compute_U0_outstream_din;
wire    lzw_compute_U0_outstream_write;
wire   [31:0] lzw_compute_U0_outlen_stream_din;
wire    lzw_compute_U0_outlen_stream_write;
wire    store_U0_ap_start;
wire    store_U0_ap_done;
wire    store_U0_ap_continue;
wire    store_U0_ap_idle;
wire    store_U0_ap_ready;
wire    store_U0_outstream_read;
wire    store_U0_m_axi_p2_AWVALID;
wire   [63:0] store_U0_m_axi_p2_AWADDR;
wire   [0:0] store_U0_m_axi_p2_AWID;
wire   [31:0] store_U0_m_axi_p2_AWLEN;
wire   [2:0] store_U0_m_axi_p2_AWSIZE;
wire   [1:0] store_U0_m_axi_p2_AWBURST;
wire   [1:0] store_U0_m_axi_p2_AWLOCK;
wire   [3:0] store_U0_m_axi_p2_AWCACHE;
wire   [2:0] store_U0_m_axi_p2_AWPROT;
wire   [3:0] store_U0_m_axi_p2_AWQOS;
wire   [3:0] store_U0_m_axi_p2_AWREGION;
wire   [0:0] store_U0_m_axi_p2_AWUSER;
wire    store_U0_m_axi_p2_WVALID;
wire   [15:0] store_U0_m_axi_p2_WDATA;
wire   [1:0] store_U0_m_axi_p2_WSTRB;
wire    store_U0_m_axi_p2_WLAST;
wire   [0:0] store_U0_m_axi_p2_WID;
wire   [0:0] store_U0_m_axi_p2_WUSER;
wire    store_U0_m_axi_p2_ARVALID;
wire   [63:0] store_U0_m_axi_p2_ARADDR;
wire   [0:0] store_U0_m_axi_p2_ARID;
wire   [31:0] store_U0_m_axi_p2_ARLEN;
wire   [2:0] store_U0_m_axi_p2_ARSIZE;
wire   [1:0] store_U0_m_axi_p2_ARBURST;
wire   [1:0] store_U0_m_axi_p2_ARLOCK;
wire   [3:0] store_U0_m_axi_p2_ARCACHE;
wire   [2:0] store_U0_m_axi_p2_ARPROT;
wire   [3:0] store_U0_m_axi_p2_ARQOS;
wire   [3:0] store_U0_m_axi_p2_ARREGION;
wire   [0:0] store_U0_m_axi_p2_ARUSER;
wire    store_U0_m_axi_p2_RREADY;
wire    store_U0_m_axi_p2_BREADY;
wire    store_U0_outlen_stream_read;
wire    store_U0_m_axi_p3_AWVALID;
wire   [63:0] store_U0_m_axi_p3_AWADDR;
wire   [0:0] store_U0_m_axi_p3_AWID;
wire   [31:0] store_U0_m_axi_p3_AWLEN;
wire   [2:0] store_U0_m_axi_p3_AWSIZE;
wire   [1:0] store_U0_m_axi_p3_AWBURST;
wire   [1:0] store_U0_m_axi_p3_AWLOCK;
wire   [3:0] store_U0_m_axi_p3_AWCACHE;
wire   [2:0] store_U0_m_axi_p3_AWPROT;
wire   [3:0] store_U0_m_axi_p3_AWQOS;
wire   [3:0] store_U0_m_axi_p3_AWREGION;
wire   [0:0] store_U0_m_axi_p3_AWUSER;
wire    store_U0_m_axi_p3_WVALID;
wire   [31:0] store_U0_m_axi_p3_WDATA;
wire   [3:0] store_U0_m_axi_p3_WSTRB;
wire    store_U0_m_axi_p3_WLAST;
wire   [0:0] store_U0_m_axi_p3_WID;
wire   [0:0] store_U0_m_axi_p3_WUSER;
wire    store_U0_m_axi_p3_ARVALID;
wire   [63:0] store_U0_m_axi_p3_ARADDR;
wire   [0:0] store_U0_m_axi_p3_ARID;
wire   [31:0] store_U0_m_axi_p3_ARLEN;
wire   [2:0] store_U0_m_axi_p3_ARSIZE;
wire   [1:0] store_U0_m_axi_p3_ARBURST;
wire   [1:0] store_U0_m_axi_p3_ARLOCK;
wire   [3:0] store_U0_m_axi_p3_ARCACHE;
wire   [2:0] store_U0_m_axi_p3_ARPROT;
wire   [3:0] store_U0_m_axi_p3_ARQOS;
wire   [3:0] store_U0_m_axi_p3_ARREGION;
wire   [0:0] store_U0_m_axi_p3_ARUSER;
wire    store_U0_m_axi_p3_RREADY;
wire    store_U0_m_axi_p3_BREADY;
wire    store_U0_outArr_read;
wire    store_U0_len_read;
wire    ap_sync_continue;
wire    instream_full_n;
wire   [7:0] instream_dout;
wire    instream_empty_n;
wire    inlen_stream_full_n;
wire   [31:0] inlen_stream_dout;
wire    inlen_stream_empty_n;
wire    output_compress_c_full_n;
wire   [63:0] output_compress_c_dout;
wire    output_compress_c_empty_n;
wire    output_length_c_full_n;
wire   [63:0] output_length_c_dout;
wire    output_length_c_empty_n;
wire    outstream_full_n;
wire   [15:0] outstream_dout;
wire    outstream_empty_n;
wire    outlen_stream_full_n;
wire   [31:0] outlen_stream_dout;
wire    outlen_stream_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
wire   [0:0] start_for_lzw_compute_U0_din;
wire    start_for_lzw_compute_U0_full_n;
wire   [0:0] start_for_lzw_compute_U0_dout;
wire    start_for_lzw_compute_U0_empty_n;
wire   [0:0] start_for_store_U0_din;
wire    start_for_store_U0_full_n;
wire   [0:0] start_for_store_U0_dout;
wire    start_for_store_U0_empty_n;
wire    lzw_compute_U0_start_full_n;
wire    lzw_compute_U0_start_write;
wire    store_U0_start_full_n;
wire    store_U0_start_write;

// power-on initialization
initial begin
#0 ap_rst_reg_2 = 1'b1;
#0 ap_rst_reg_1 = 1'b1;
#0 ap_rst_n_inv = 1'b1;
end

encoding_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .buff(buff),
    .input_length(input_length),
    .output_compress(output_compress),
    .output_length(output_length),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_continue(ap_continue),
    .ap_idle(ap_idle)
);

encoding_p0_m_axi #(
    .CONSERVATIVE( 0 ),
    .USER_DW( 8 ),
    .USER_AW( 64 ),
    .USER_MAXREQS( 69 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_P0_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_P0_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_P0_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_P0_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_P0_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_P0_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_P0_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_P0_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_P0_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_P0_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_P0_CACHE_VALUE ))
p0_m_axi_U(
    .AWVALID(m_axi_p0_AWVALID),
    .AWREADY(m_axi_p0_AWREADY),
    .AWADDR(m_axi_p0_AWADDR),
    .AWID(m_axi_p0_AWID),
    .AWLEN(m_axi_p0_AWLEN),
    .AWSIZE(m_axi_p0_AWSIZE),
    .AWBURST(m_axi_p0_AWBURST),
    .AWLOCK(m_axi_p0_AWLOCK),
    .AWCACHE(m_axi_p0_AWCACHE),
    .AWPROT(m_axi_p0_AWPROT),
    .AWQOS(m_axi_p0_AWQOS),
    .AWREGION(m_axi_p0_AWREGION),
    .AWUSER(m_axi_p0_AWUSER),
    .WVALID(m_axi_p0_WVALID),
    .WREADY(m_axi_p0_WREADY),
    .WDATA(m_axi_p0_WDATA),
    .WSTRB(m_axi_p0_WSTRB),
    .WLAST(m_axi_p0_WLAST),
    .WID(m_axi_p0_WID),
    .WUSER(m_axi_p0_WUSER),
    .ARVALID(m_axi_p0_ARVALID),
    .ARREADY(m_axi_p0_ARREADY),
    .ARADDR(m_axi_p0_ARADDR),
    .ARID(m_axi_p0_ARID),
    .ARLEN(m_axi_p0_ARLEN),
    .ARSIZE(m_axi_p0_ARSIZE),
    .ARBURST(m_axi_p0_ARBURST),
    .ARLOCK(m_axi_p0_ARLOCK),
    .ARCACHE(m_axi_p0_ARCACHE),
    .ARPROT(m_axi_p0_ARPROT),
    .ARQOS(m_axi_p0_ARQOS),
    .ARREGION(m_axi_p0_ARREGION),
    .ARUSER(m_axi_p0_ARUSER),
    .RVALID(m_axi_p0_RVALID),
    .RREADY(m_axi_p0_RREADY),
    .RDATA(m_axi_p0_RDATA),
    .RLAST(m_axi_p0_RLAST),
    .RID(m_axi_p0_RID),
    .RUSER(m_axi_p0_RUSER),
    .RRESP(m_axi_p0_RRESP),
    .BVALID(m_axi_p0_BVALID),
    .BREADY(m_axi_p0_BREADY),
    .BRESP(m_axi_p0_BRESP),
    .BID(m_axi_p0_BID),
    .BUSER(m_axi_p0_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(load6_U0_m_axi_p0_ARVALID),
    .I_ARREADY(p0_ARREADY),
    .I_ARADDR(load6_U0_m_axi_p0_ARADDR),
    .I_ARID(load6_U0_m_axi_p0_ARID),
    .I_ARLEN(load6_U0_m_axi_p0_ARLEN),
    .I_ARSIZE(load6_U0_m_axi_p0_ARSIZE),
    .I_ARLOCK(load6_U0_m_axi_p0_ARLOCK),
    .I_ARCACHE(load6_U0_m_axi_p0_ARCACHE),
    .I_ARQOS(load6_U0_m_axi_p0_ARQOS),
    .I_ARPROT(load6_U0_m_axi_p0_ARPROT),
    .I_ARUSER(load6_U0_m_axi_p0_ARUSER),
    .I_ARBURST(load6_U0_m_axi_p0_ARBURST),
    .I_ARREGION(load6_U0_m_axi_p0_ARREGION),
    .I_RVALID(p0_RVALID),
    .I_RREADY(load6_U0_m_axi_p0_RREADY),
    .I_RDATA(p0_RDATA),
    .I_RID(p0_RID),
    .I_RUSER(p0_RUSER),
    .I_RRESP(p0_RRESP),
    .I_RLAST(p0_RLAST),
    .I_AWVALID(1'b0),
    .I_AWREADY(p0_AWREADY),
    .I_AWADDR(64'd0),
    .I_AWID(1'd0),
    .I_AWLEN(32'd0),
    .I_AWSIZE(3'd0),
    .I_AWLOCK(2'd0),
    .I_AWCACHE(4'd0),
    .I_AWQOS(4'd0),
    .I_AWPROT(3'd0),
    .I_AWUSER(1'd0),
    .I_AWBURST(2'd0),
    .I_AWREGION(4'd0),
    .I_WVALID(1'b0),
    .I_WREADY(p0_WREADY),
    .I_WDATA(8'd0),
    .I_WID(1'd0),
    .I_WUSER(1'd0),
    .I_WLAST(1'b0),
    .I_WSTRB(1'd0),
    .I_BVALID(p0_BVALID),
    .I_BREADY(1'b0),
    .I_BRESP(p0_BRESP),
    .I_BID(p0_BID),
    .I_BUSER(p0_BUSER)
);

encoding_p1_m_axi #(
    .CONSERVATIVE( 0 ),
    .USER_DW( 32 ),
    .USER_AW( 64 ),
    .USER_MAXREQS( 69 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_P1_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_P1_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_P1_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_P1_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_P1_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_P1_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_P1_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_P1_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_P1_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_P1_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_P1_CACHE_VALUE ))
p1_m_axi_U(
    .AWVALID(m_axi_p1_AWVALID),
    .AWREADY(m_axi_p1_AWREADY),
    .AWADDR(m_axi_p1_AWADDR),
    .AWID(m_axi_p1_AWID),
    .AWLEN(m_axi_p1_AWLEN),
    .AWSIZE(m_axi_p1_AWSIZE),
    .AWBURST(m_axi_p1_AWBURST),
    .AWLOCK(m_axi_p1_AWLOCK),
    .AWCACHE(m_axi_p1_AWCACHE),
    .AWPROT(m_axi_p1_AWPROT),
    .AWQOS(m_axi_p1_AWQOS),
    .AWREGION(m_axi_p1_AWREGION),
    .AWUSER(m_axi_p1_AWUSER),
    .WVALID(m_axi_p1_WVALID),
    .WREADY(m_axi_p1_WREADY),
    .WDATA(m_axi_p1_WDATA),
    .WSTRB(m_axi_p1_WSTRB),
    .WLAST(m_axi_p1_WLAST),
    .WID(m_axi_p1_WID),
    .WUSER(m_axi_p1_WUSER),
    .ARVALID(m_axi_p1_ARVALID),
    .ARREADY(m_axi_p1_ARREADY),
    .ARADDR(m_axi_p1_ARADDR),
    .ARID(m_axi_p1_ARID),
    .ARLEN(m_axi_p1_ARLEN),
    .ARSIZE(m_axi_p1_ARSIZE),
    .ARBURST(m_axi_p1_ARBURST),
    .ARLOCK(m_axi_p1_ARLOCK),
    .ARCACHE(m_axi_p1_ARCACHE),
    .ARPROT(m_axi_p1_ARPROT),
    .ARQOS(m_axi_p1_ARQOS),
    .ARREGION(m_axi_p1_ARREGION),
    .ARUSER(m_axi_p1_ARUSER),
    .RVALID(m_axi_p1_RVALID),
    .RREADY(m_axi_p1_RREADY),
    .RDATA(m_axi_p1_RDATA),
    .RLAST(m_axi_p1_RLAST),
    .RID(m_axi_p1_RID),
    .RUSER(m_axi_p1_RUSER),
    .RRESP(m_axi_p1_RRESP),
    .BVALID(m_axi_p1_BVALID),
    .BREADY(m_axi_p1_BREADY),
    .BRESP(m_axi_p1_BRESP),
    .BID(m_axi_p1_BID),
    .BUSER(m_axi_p1_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(load6_U0_m_axi_p1_ARVALID),
    .I_ARREADY(p1_ARREADY),
    .I_ARADDR(load6_U0_m_axi_p1_ARADDR),
    .I_ARID(load6_U0_m_axi_p1_ARID),
    .I_ARLEN(load6_U0_m_axi_p1_ARLEN),
    .I_ARSIZE(load6_U0_m_axi_p1_ARSIZE),
    .I_ARLOCK(load6_U0_m_axi_p1_ARLOCK),
    .I_ARCACHE(load6_U0_m_axi_p1_ARCACHE),
    .I_ARQOS(load6_U0_m_axi_p1_ARQOS),
    .I_ARPROT(load6_U0_m_axi_p1_ARPROT),
    .I_ARUSER(load6_U0_m_axi_p1_ARUSER),
    .I_ARBURST(load6_U0_m_axi_p1_ARBURST),
    .I_ARREGION(load6_U0_m_axi_p1_ARREGION),
    .I_RVALID(p1_RVALID),
    .I_RREADY(load6_U0_m_axi_p1_RREADY),
    .I_RDATA(p1_RDATA),
    .I_RID(p1_RID),
    .I_RUSER(p1_RUSER),
    .I_RRESP(p1_RRESP),
    .I_RLAST(p1_RLAST),
    .I_AWVALID(1'b0),
    .I_AWREADY(p1_AWREADY),
    .I_AWADDR(64'd0),
    .I_AWID(1'd0),
    .I_AWLEN(32'd0),
    .I_AWSIZE(3'd0),
    .I_AWLOCK(2'd0),
    .I_AWCACHE(4'd0),
    .I_AWQOS(4'd0),
    .I_AWPROT(3'd0),
    .I_AWUSER(1'd0),
    .I_AWBURST(2'd0),
    .I_AWREGION(4'd0),
    .I_WVALID(1'b0),
    .I_WREADY(p1_WREADY),
    .I_WDATA(32'd0),
    .I_WID(1'd0),
    .I_WUSER(1'd0),
    .I_WLAST(1'b0),
    .I_WSTRB(4'd0),
    .I_BVALID(p1_BVALID),
    .I_BREADY(1'b0),
    .I_BRESP(p1_BRESP),
    .I_BID(p1_BID),
    .I_BUSER(p1_BUSER)
);

encoding_p2_m_axi #(
    .CONSERVATIVE( 0 ),
    .USER_DW( 16 ),
    .USER_AW( 64 ),
    .USER_MAXREQS( 69 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_P2_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_P2_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_P2_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_P2_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_P2_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_P2_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_P2_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_P2_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_P2_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_P2_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_P2_CACHE_VALUE ))
p2_m_axi_U(
    .AWVALID(m_axi_p2_AWVALID),
    .AWREADY(m_axi_p2_AWREADY),
    .AWADDR(m_axi_p2_AWADDR),
    .AWID(m_axi_p2_AWID),
    .AWLEN(m_axi_p2_AWLEN),
    .AWSIZE(m_axi_p2_AWSIZE),
    .AWBURST(m_axi_p2_AWBURST),
    .AWLOCK(m_axi_p2_AWLOCK),
    .AWCACHE(m_axi_p2_AWCACHE),
    .AWPROT(m_axi_p2_AWPROT),
    .AWQOS(m_axi_p2_AWQOS),
    .AWREGION(m_axi_p2_AWREGION),
    .AWUSER(m_axi_p2_AWUSER),
    .WVALID(m_axi_p2_WVALID),
    .WREADY(m_axi_p2_WREADY),
    .WDATA(m_axi_p2_WDATA),
    .WSTRB(m_axi_p2_WSTRB),
    .WLAST(m_axi_p2_WLAST),
    .WID(m_axi_p2_WID),
    .WUSER(m_axi_p2_WUSER),
    .ARVALID(m_axi_p2_ARVALID),
    .ARREADY(m_axi_p2_ARREADY),
    .ARADDR(m_axi_p2_ARADDR),
    .ARID(m_axi_p2_ARID),
    .ARLEN(m_axi_p2_ARLEN),
    .ARSIZE(m_axi_p2_ARSIZE),
    .ARBURST(m_axi_p2_ARBURST),
    .ARLOCK(m_axi_p2_ARLOCK),
    .ARCACHE(m_axi_p2_ARCACHE),
    .ARPROT(m_axi_p2_ARPROT),
    .ARQOS(m_axi_p2_ARQOS),
    .ARREGION(m_axi_p2_ARREGION),
    .ARUSER(m_axi_p2_ARUSER),
    .RVALID(m_axi_p2_RVALID),
    .RREADY(m_axi_p2_RREADY),
    .RDATA(m_axi_p2_RDATA),
    .RLAST(m_axi_p2_RLAST),
    .RID(m_axi_p2_RID),
    .RUSER(m_axi_p2_RUSER),
    .RRESP(m_axi_p2_RRESP),
    .BVALID(m_axi_p2_BVALID),
    .BREADY(m_axi_p2_BREADY),
    .BRESP(m_axi_p2_BRESP),
    .BID(m_axi_p2_BID),
    .BUSER(m_axi_p2_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(1'b0),
    .I_ARREADY(p2_ARREADY),
    .I_ARADDR(64'd0),
    .I_ARID(1'd0),
    .I_ARLEN(32'd0),
    .I_ARSIZE(3'd0),
    .I_ARLOCK(2'd0),
    .I_ARCACHE(4'd0),
    .I_ARQOS(4'd0),
    .I_ARPROT(3'd0),
    .I_ARUSER(1'd0),
    .I_ARBURST(2'd0),
    .I_ARREGION(4'd0),
    .I_RVALID(p2_RVALID),
    .I_RREADY(1'b0),
    .I_RDATA(p2_RDATA),
    .I_RID(p2_RID),
    .I_RUSER(p2_RUSER),
    .I_RRESP(p2_RRESP),
    .I_RLAST(p2_RLAST),
    .I_AWVALID(store_U0_m_axi_p2_AWVALID),
    .I_AWREADY(p2_AWREADY),
    .I_AWADDR(store_U0_m_axi_p2_AWADDR),
    .I_AWID(store_U0_m_axi_p2_AWID),
    .I_AWLEN(store_U0_m_axi_p2_AWLEN),
    .I_AWSIZE(store_U0_m_axi_p2_AWSIZE),
    .I_AWLOCK(store_U0_m_axi_p2_AWLOCK),
    .I_AWCACHE(store_U0_m_axi_p2_AWCACHE),
    .I_AWQOS(store_U0_m_axi_p2_AWQOS),
    .I_AWPROT(store_U0_m_axi_p2_AWPROT),
    .I_AWUSER(store_U0_m_axi_p2_AWUSER),
    .I_AWBURST(store_U0_m_axi_p2_AWBURST),
    .I_AWREGION(store_U0_m_axi_p2_AWREGION),
    .I_WVALID(store_U0_m_axi_p2_WVALID),
    .I_WREADY(p2_WREADY),
    .I_WDATA(store_U0_m_axi_p2_WDATA),
    .I_WID(store_U0_m_axi_p2_WID),
    .I_WUSER(store_U0_m_axi_p2_WUSER),
    .I_WLAST(store_U0_m_axi_p2_WLAST),
    .I_WSTRB(store_U0_m_axi_p2_WSTRB),
    .I_BVALID(p2_BVALID),
    .I_BREADY(store_U0_m_axi_p2_BREADY),
    .I_BRESP(p2_BRESP),
    .I_BID(p2_BID),
    .I_BUSER(p2_BUSER)
);

encoding_p3_m_axi #(
    .CONSERVATIVE( 0 ),
    .USER_DW( 32 ),
    .USER_AW( 64 ),
    .USER_MAXREQS( 69 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_P3_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_P3_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_P3_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_P3_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_P3_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_P3_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_P3_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_P3_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_P3_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_P3_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_P3_CACHE_VALUE ))
p3_m_axi_U(
    .AWVALID(m_axi_p3_AWVALID),
    .AWREADY(m_axi_p3_AWREADY),
    .AWADDR(m_axi_p3_AWADDR),
    .AWID(m_axi_p3_AWID),
    .AWLEN(m_axi_p3_AWLEN),
    .AWSIZE(m_axi_p3_AWSIZE),
    .AWBURST(m_axi_p3_AWBURST),
    .AWLOCK(m_axi_p3_AWLOCK),
    .AWCACHE(m_axi_p3_AWCACHE),
    .AWPROT(m_axi_p3_AWPROT),
    .AWQOS(m_axi_p3_AWQOS),
    .AWREGION(m_axi_p3_AWREGION),
    .AWUSER(m_axi_p3_AWUSER),
    .WVALID(m_axi_p3_WVALID),
    .WREADY(m_axi_p3_WREADY),
    .WDATA(m_axi_p3_WDATA),
    .WSTRB(m_axi_p3_WSTRB),
    .WLAST(m_axi_p3_WLAST),
    .WID(m_axi_p3_WID),
    .WUSER(m_axi_p3_WUSER),
    .ARVALID(m_axi_p3_ARVALID),
    .ARREADY(m_axi_p3_ARREADY),
    .ARADDR(m_axi_p3_ARADDR),
    .ARID(m_axi_p3_ARID),
    .ARLEN(m_axi_p3_ARLEN),
    .ARSIZE(m_axi_p3_ARSIZE),
    .ARBURST(m_axi_p3_ARBURST),
    .ARLOCK(m_axi_p3_ARLOCK),
    .ARCACHE(m_axi_p3_ARCACHE),
    .ARPROT(m_axi_p3_ARPROT),
    .ARQOS(m_axi_p3_ARQOS),
    .ARREGION(m_axi_p3_ARREGION),
    .ARUSER(m_axi_p3_ARUSER),
    .RVALID(m_axi_p3_RVALID),
    .RREADY(m_axi_p3_RREADY),
    .RDATA(m_axi_p3_RDATA),
    .RLAST(m_axi_p3_RLAST),
    .RID(m_axi_p3_RID),
    .RUSER(m_axi_p3_RUSER),
    .RRESP(m_axi_p3_RRESP),
    .BVALID(m_axi_p3_BVALID),
    .BREADY(m_axi_p3_BREADY),
    .BRESP(m_axi_p3_BRESP),
    .BID(m_axi_p3_BID),
    .BUSER(m_axi_p3_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(1'b0),
    .I_ARREADY(p3_ARREADY),
    .I_ARADDR(64'd0),
    .I_ARID(1'd0),
    .I_ARLEN(32'd0),
    .I_ARSIZE(3'd0),
    .I_ARLOCK(2'd0),
    .I_ARCACHE(4'd0),
    .I_ARQOS(4'd0),
    .I_ARPROT(3'd0),
    .I_ARUSER(1'd0),
    .I_ARBURST(2'd0),
    .I_ARREGION(4'd0),
    .I_RVALID(p3_RVALID),
    .I_RREADY(1'b0),
    .I_RDATA(p3_RDATA),
    .I_RID(p3_RID),
    .I_RUSER(p3_RUSER),
    .I_RRESP(p3_RRESP),
    .I_RLAST(p3_RLAST),
    .I_AWVALID(store_U0_m_axi_p3_AWVALID),
    .I_AWREADY(p3_AWREADY),
    .I_AWADDR(store_U0_m_axi_p3_AWADDR),
    .I_AWID(store_U0_m_axi_p3_AWID),
    .I_AWLEN(store_U0_m_axi_p3_AWLEN),
    .I_AWSIZE(store_U0_m_axi_p3_AWSIZE),
    .I_AWLOCK(store_U0_m_axi_p3_AWLOCK),
    .I_AWCACHE(store_U0_m_axi_p3_AWCACHE),
    .I_AWQOS(store_U0_m_axi_p3_AWQOS),
    .I_AWPROT(store_U0_m_axi_p3_AWPROT),
    .I_AWUSER(store_U0_m_axi_p3_AWUSER),
    .I_AWBURST(store_U0_m_axi_p3_AWBURST),
    .I_AWREGION(store_U0_m_axi_p3_AWREGION),
    .I_WVALID(store_U0_m_axi_p3_WVALID),
    .I_WREADY(p3_WREADY),
    .I_WDATA(store_U0_m_axi_p3_WDATA),
    .I_WID(store_U0_m_axi_p3_WID),
    .I_WUSER(store_U0_m_axi_p3_WUSER),
    .I_WLAST(store_U0_m_axi_p3_WLAST),
    .I_WSTRB(store_U0_m_axi_p3_WSTRB),
    .I_BVALID(p3_BVALID),
    .I_BREADY(store_U0_m_axi_p3_BREADY),
    .I_BRESP(p3_BRESP),
    .I_BID(p3_BID),
    .I_BUSER(p3_BUSER)
);

encoding_load6 load6_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(load6_U0_ap_start),
    .start_full_n(load6_U0_start_full_n),
    .ap_done(load6_U0_ap_done),
    .ap_continue(load6_U0_ap_continue),
    .ap_idle(load6_U0_ap_idle),
    .ap_ready(load6_U0_ap_ready),
    .start_out(load6_U0_start_out),
    .start_write(load6_U0_start_write),
    .m_axi_p0_AWVALID(load6_U0_m_axi_p0_AWVALID),
    .m_axi_p0_AWREADY(1'b0),
    .m_axi_p0_AWADDR(load6_U0_m_axi_p0_AWADDR),
    .m_axi_p0_AWID(load6_U0_m_axi_p0_AWID),
    .m_axi_p0_AWLEN(load6_U0_m_axi_p0_AWLEN),
    .m_axi_p0_AWSIZE(load6_U0_m_axi_p0_AWSIZE),
    .m_axi_p0_AWBURST(load6_U0_m_axi_p0_AWBURST),
    .m_axi_p0_AWLOCK(load6_U0_m_axi_p0_AWLOCK),
    .m_axi_p0_AWCACHE(load6_U0_m_axi_p0_AWCACHE),
    .m_axi_p0_AWPROT(load6_U0_m_axi_p0_AWPROT),
    .m_axi_p0_AWQOS(load6_U0_m_axi_p0_AWQOS),
    .m_axi_p0_AWREGION(load6_U0_m_axi_p0_AWREGION),
    .m_axi_p0_AWUSER(load6_U0_m_axi_p0_AWUSER),
    .m_axi_p0_WVALID(load6_U0_m_axi_p0_WVALID),
    .m_axi_p0_WREADY(1'b0),
    .m_axi_p0_WDATA(load6_U0_m_axi_p0_WDATA),
    .m_axi_p0_WSTRB(load6_U0_m_axi_p0_WSTRB),
    .m_axi_p0_WLAST(load6_U0_m_axi_p0_WLAST),
    .m_axi_p0_WID(load6_U0_m_axi_p0_WID),
    .m_axi_p0_WUSER(load6_U0_m_axi_p0_WUSER),
    .m_axi_p0_ARVALID(load6_U0_m_axi_p0_ARVALID),
    .m_axi_p0_ARREADY(p0_ARREADY),
    .m_axi_p0_ARADDR(load6_U0_m_axi_p0_ARADDR),
    .m_axi_p0_ARID(load6_U0_m_axi_p0_ARID),
    .m_axi_p0_ARLEN(load6_U0_m_axi_p0_ARLEN),
    .m_axi_p0_ARSIZE(load6_U0_m_axi_p0_ARSIZE),
    .m_axi_p0_ARBURST(load6_U0_m_axi_p0_ARBURST),
    .m_axi_p0_ARLOCK(load6_U0_m_axi_p0_ARLOCK),
    .m_axi_p0_ARCACHE(load6_U0_m_axi_p0_ARCACHE),
    .m_axi_p0_ARPROT(load6_U0_m_axi_p0_ARPROT),
    .m_axi_p0_ARQOS(load6_U0_m_axi_p0_ARQOS),
    .m_axi_p0_ARREGION(load6_U0_m_axi_p0_ARREGION),
    .m_axi_p0_ARUSER(load6_U0_m_axi_p0_ARUSER),
    .m_axi_p0_RVALID(p0_RVALID),
    .m_axi_p0_RREADY(load6_U0_m_axi_p0_RREADY),
    .m_axi_p0_RDATA(p0_RDATA),
    .m_axi_p0_RLAST(p0_RLAST),
    .m_axi_p0_RID(p0_RID),
    .m_axi_p0_RUSER(p0_RUSER),
    .m_axi_p0_RRESP(p0_RRESP),
    .m_axi_p0_BVALID(1'b0),
    .m_axi_p0_BREADY(load6_U0_m_axi_p0_BREADY),
    .m_axi_p0_BRESP(2'd0),
    .m_axi_p0_BID(1'd0),
    .m_axi_p0_BUSER(1'd0),
    .instream_din(load6_U0_instream_din),
    .instream_full_n(instream_full_n),
    .instream_write(load6_U0_instream_write),
    .m_axi_p1_AWVALID(load6_U0_m_axi_p1_AWVALID),
    .m_axi_p1_AWREADY(1'b0),
    .m_axi_p1_AWADDR(load6_U0_m_axi_p1_AWADDR),
    .m_axi_p1_AWID(load6_U0_m_axi_p1_AWID),
    .m_axi_p1_AWLEN(load6_U0_m_axi_p1_AWLEN),
    .m_axi_p1_AWSIZE(load6_U0_m_axi_p1_AWSIZE),
    .m_axi_p1_AWBURST(load6_U0_m_axi_p1_AWBURST),
    .m_axi_p1_AWLOCK(load6_U0_m_axi_p1_AWLOCK),
    .m_axi_p1_AWCACHE(load6_U0_m_axi_p1_AWCACHE),
    .m_axi_p1_AWPROT(load6_U0_m_axi_p1_AWPROT),
    .m_axi_p1_AWQOS(load6_U0_m_axi_p1_AWQOS),
    .m_axi_p1_AWREGION(load6_U0_m_axi_p1_AWREGION),
    .m_axi_p1_AWUSER(load6_U0_m_axi_p1_AWUSER),
    .m_axi_p1_WVALID(load6_U0_m_axi_p1_WVALID),
    .m_axi_p1_WREADY(1'b0),
    .m_axi_p1_WDATA(load6_U0_m_axi_p1_WDATA),
    .m_axi_p1_WSTRB(load6_U0_m_axi_p1_WSTRB),
    .m_axi_p1_WLAST(load6_U0_m_axi_p1_WLAST),
    .m_axi_p1_WID(load6_U0_m_axi_p1_WID),
    .m_axi_p1_WUSER(load6_U0_m_axi_p1_WUSER),
    .m_axi_p1_ARVALID(load6_U0_m_axi_p1_ARVALID),
    .m_axi_p1_ARREADY(p1_ARREADY),
    .m_axi_p1_ARADDR(load6_U0_m_axi_p1_ARADDR),
    .m_axi_p1_ARID(load6_U0_m_axi_p1_ARID),
    .m_axi_p1_ARLEN(load6_U0_m_axi_p1_ARLEN),
    .m_axi_p1_ARSIZE(load6_U0_m_axi_p1_ARSIZE),
    .m_axi_p1_ARBURST(load6_U0_m_axi_p1_ARBURST),
    .m_axi_p1_ARLOCK(load6_U0_m_axi_p1_ARLOCK),
    .m_axi_p1_ARCACHE(load6_U0_m_axi_p1_ARCACHE),
    .m_axi_p1_ARPROT(load6_U0_m_axi_p1_ARPROT),
    .m_axi_p1_ARQOS(load6_U0_m_axi_p1_ARQOS),
    .m_axi_p1_ARREGION(load6_U0_m_axi_p1_ARREGION),
    .m_axi_p1_ARUSER(load6_U0_m_axi_p1_ARUSER),
    .m_axi_p1_RVALID(p1_RVALID),
    .m_axi_p1_RREADY(load6_U0_m_axi_p1_RREADY),
    .m_axi_p1_RDATA(p1_RDATA),
    .m_axi_p1_RLAST(p1_RLAST),
    .m_axi_p1_RID(p1_RID),
    .m_axi_p1_RUSER(p1_RUSER),
    .m_axi_p1_RRESP(p1_RRESP),
    .m_axi_p1_BVALID(1'b0),
    .m_axi_p1_BREADY(load6_U0_m_axi_p1_BREADY),
    .m_axi_p1_BRESP(2'd0),
    .m_axi_p1_BID(1'd0),
    .m_axi_p1_BUSER(1'd0),
    .inlen_stream_din(load6_U0_inlen_stream_din),
    .inlen_stream_full_n(inlen_stream_full_n),
    .inlen_stream_write(load6_U0_inlen_stream_write),
    .input_r(buff),
    .len(input_length),
    .output_compress(output_compress),
    .output_length(output_length),
    .output_compress_out_din(load6_U0_output_compress_out_din),
    .output_compress_out_full_n(output_compress_c_full_n),
    .output_compress_out_write(load6_U0_output_compress_out_write),
    .output_length_out_din(load6_U0_output_length_out_din),
    .output_length_out_full_n(output_length_c_full_n),
    .output_length_out_write(load6_U0_output_length_out_write)
);

encoding_lzw_compute lzw_compute_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(lzw_compute_U0_ap_start),
    .ap_done(lzw_compute_U0_ap_done),
    .ap_continue(lzw_compute_U0_ap_continue),
    .ap_idle(lzw_compute_U0_ap_idle),
    .ap_ready(lzw_compute_U0_ap_ready),
    .instream_dout(instream_dout),
    .instream_empty_n(instream_empty_n),
    .instream_read(lzw_compute_U0_instream_read),
    .inlen_stream_dout(inlen_stream_dout),
    .inlen_stream_empty_n(inlen_stream_empty_n),
    .inlen_stream_read(lzw_compute_U0_inlen_stream_read),
    .outstream_din(lzw_compute_U0_outstream_din),
    .outstream_full_n(outstream_full_n),
    .outstream_write(lzw_compute_U0_outstream_write),
    .outlen_stream_din(lzw_compute_U0_outlen_stream_din),
    .outlen_stream_full_n(outlen_stream_full_n),
    .outlen_stream_write(lzw_compute_U0_outlen_stream_write)
);

encoding_store store_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(store_U0_ap_start),
    .ap_done(store_U0_ap_done),
    .ap_continue(store_U0_ap_continue),
    .ap_idle(store_U0_ap_idle),
    .ap_ready(store_U0_ap_ready),
    .outstream_dout(outstream_dout),
    .outstream_empty_n(outstream_empty_n),
    .outstream_read(store_U0_outstream_read),
    .m_axi_p2_AWVALID(store_U0_m_axi_p2_AWVALID),
    .m_axi_p2_AWREADY(p2_AWREADY),
    .m_axi_p2_AWADDR(store_U0_m_axi_p2_AWADDR),
    .m_axi_p2_AWID(store_U0_m_axi_p2_AWID),
    .m_axi_p2_AWLEN(store_U0_m_axi_p2_AWLEN),
    .m_axi_p2_AWSIZE(store_U0_m_axi_p2_AWSIZE),
    .m_axi_p2_AWBURST(store_U0_m_axi_p2_AWBURST),
    .m_axi_p2_AWLOCK(store_U0_m_axi_p2_AWLOCK),
    .m_axi_p2_AWCACHE(store_U0_m_axi_p2_AWCACHE),
    .m_axi_p2_AWPROT(store_U0_m_axi_p2_AWPROT),
    .m_axi_p2_AWQOS(store_U0_m_axi_p2_AWQOS),
    .m_axi_p2_AWREGION(store_U0_m_axi_p2_AWREGION),
    .m_axi_p2_AWUSER(store_U0_m_axi_p2_AWUSER),
    .m_axi_p2_WVALID(store_U0_m_axi_p2_WVALID),
    .m_axi_p2_WREADY(p2_WREADY),
    .m_axi_p2_WDATA(store_U0_m_axi_p2_WDATA),
    .m_axi_p2_WSTRB(store_U0_m_axi_p2_WSTRB),
    .m_axi_p2_WLAST(store_U0_m_axi_p2_WLAST),
    .m_axi_p2_WID(store_U0_m_axi_p2_WID),
    .m_axi_p2_WUSER(store_U0_m_axi_p2_WUSER),
    .m_axi_p2_ARVALID(store_U0_m_axi_p2_ARVALID),
    .m_axi_p2_ARREADY(1'b0),
    .m_axi_p2_ARADDR(store_U0_m_axi_p2_ARADDR),
    .m_axi_p2_ARID(store_U0_m_axi_p2_ARID),
    .m_axi_p2_ARLEN(store_U0_m_axi_p2_ARLEN),
    .m_axi_p2_ARSIZE(store_U0_m_axi_p2_ARSIZE),
    .m_axi_p2_ARBURST(store_U0_m_axi_p2_ARBURST),
    .m_axi_p2_ARLOCK(store_U0_m_axi_p2_ARLOCK),
    .m_axi_p2_ARCACHE(store_U0_m_axi_p2_ARCACHE),
    .m_axi_p2_ARPROT(store_U0_m_axi_p2_ARPROT),
    .m_axi_p2_ARQOS(store_U0_m_axi_p2_ARQOS),
    .m_axi_p2_ARREGION(store_U0_m_axi_p2_ARREGION),
    .m_axi_p2_ARUSER(store_U0_m_axi_p2_ARUSER),
    .m_axi_p2_RVALID(1'b0),
    .m_axi_p2_RREADY(store_U0_m_axi_p2_RREADY),
    .m_axi_p2_RDATA(16'd0),
    .m_axi_p2_RLAST(1'b0),
    .m_axi_p2_RID(1'd0),
    .m_axi_p2_RUSER(1'd0),
    .m_axi_p2_RRESP(2'd0),
    .m_axi_p2_BVALID(p2_BVALID),
    .m_axi_p2_BREADY(store_U0_m_axi_p2_BREADY),
    .m_axi_p2_BRESP(p2_BRESP),
    .m_axi_p2_BID(p2_BID),
    .m_axi_p2_BUSER(p2_BUSER),
    .outlen_stream_dout(outlen_stream_dout),
    .outlen_stream_empty_n(outlen_stream_empty_n),
    .outlen_stream_read(store_U0_outlen_stream_read),
    .m_axi_p3_AWVALID(store_U0_m_axi_p3_AWVALID),
    .m_axi_p3_AWREADY(p3_AWREADY),
    .m_axi_p3_AWADDR(store_U0_m_axi_p3_AWADDR),
    .m_axi_p3_AWID(store_U0_m_axi_p3_AWID),
    .m_axi_p3_AWLEN(store_U0_m_axi_p3_AWLEN),
    .m_axi_p3_AWSIZE(store_U0_m_axi_p3_AWSIZE),
    .m_axi_p3_AWBURST(store_U0_m_axi_p3_AWBURST),
    .m_axi_p3_AWLOCK(store_U0_m_axi_p3_AWLOCK),
    .m_axi_p3_AWCACHE(store_U0_m_axi_p3_AWCACHE),
    .m_axi_p3_AWPROT(store_U0_m_axi_p3_AWPROT),
    .m_axi_p3_AWQOS(store_U0_m_axi_p3_AWQOS),
    .m_axi_p3_AWREGION(store_U0_m_axi_p3_AWREGION),
    .m_axi_p3_AWUSER(store_U0_m_axi_p3_AWUSER),
    .m_axi_p3_WVALID(store_U0_m_axi_p3_WVALID),
    .m_axi_p3_WREADY(p3_WREADY),
    .m_axi_p3_WDATA(store_U0_m_axi_p3_WDATA),
    .m_axi_p3_WSTRB(store_U0_m_axi_p3_WSTRB),
    .m_axi_p3_WLAST(store_U0_m_axi_p3_WLAST),
    .m_axi_p3_WID(store_U0_m_axi_p3_WID),
    .m_axi_p3_WUSER(store_U0_m_axi_p3_WUSER),
    .m_axi_p3_ARVALID(store_U0_m_axi_p3_ARVALID),
    .m_axi_p3_ARREADY(1'b0),
    .m_axi_p3_ARADDR(store_U0_m_axi_p3_ARADDR),
    .m_axi_p3_ARID(store_U0_m_axi_p3_ARID),
    .m_axi_p3_ARLEN(store_U0_m_axi_p3_ARLEN),
    .m_axi_p3_ARSIZE(store_U0_m_axi_p3_ARSIZE),
    .m_axi_p3_ARBURST(store_U0_m_axi_p3_ARBURST),
    .m_axi_p3_ARLOCK(store_U0_m_axi_p3_ARLOCK),
    .m_axi_p3_ARCACHE(store_U0_m_axi_p3_ARCACHE),
    .m_axi_p3_ARPROT(store_U0_m_axi_p3_ARPROT),
    .m_axi_p3_ARQOS(store_U0_m_axi_p3_ARQOS),
    .m_axi_p3_ARREGION(store_U0_m_axi_p3_ARREGION),
    .m_axi_p3_ARUSER(store_U0_m_axi_p3_ARUSER),
    .m_axi_p3_RVALID(1'b0),
    .m_axi_p3_RREADY(store_U0_m_axi_p3_RREADY),
    .m_axi_p3_RDATA(32'd0),
    .m_axi_p3_RLAST(1'b0),
    .m_axi_p3_RID(1'd0),
    .m_axi_p3_RUSER(1'd0),
    .m_axi_p3_RRESP(2'd0),
    .m_axi_p3_BVALID(p3_BVALID),
    .m_axi_p3_BREADY(store_U0_m_axi_p3_BREADY),
    .m_axi_p3_BRESP(p3_BRESP),
    .m_axi_p3_BID(p3_BID),
    .m_axi_p3_BUSER(p3_BUSER),
    .outArr_dout(output_compress_c_dout),
    .outArr_empty_n(output_compress_c_empty_n),
    .outArr_read(store_U0_outArr_read),
    .len_dout(output_length_c_dout),
    .len_empty_n(output_length_c_empty_n),
    .len_read(store_U0_len_read)
);

encoding_fifo_w8_d8192_A instream_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(load6_U0_instream_din),
    .if_full_n(instream_full_n),
    .if_write(load6_U0_instream_write),
    .if_dout(instream_dout),
    .if_empty_n(instream_empty_n),
    .if_read(lzw_compute_U0_instream_read)
);

encoding_fifo_w32_d8192_A inlen_stream_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(load6_U0_inlen_stream_din),
    .if_full_n(inlen_stream_full_n),
    .if_write(load6_U0_inlen_stream_write),
    .if_dout(inlen_stream_dout),
    .if_empty_n(inlen_stream_empty_n),
    .if_read(lzw_compute_U0_inlen_stream_read)
);

encoding_fifo_w64_d3_S output_compress_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(load6_U0_output_compress_out_din),
    .if_full_n(output_compress_c_full_n),
    .if_write(load6_U0_output_compress_out_write),
    .if_dout(output_compress_c_dout),
    .if_empty_n(output_compress_c_empty_n),
    .if_read(store_U0_outArr_read)
);

encoding_fifo_w64_d3_S output_length_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(load6_U0_output_length_out_din),
    .if_full_n(output_length_c_full_n),
    .if_write(load6_U0_output_length_out_write),
    .if_dout(output_length_c_dout),
    .if_empty_n(output_length_c_empty_n),
    .if_read(store_U0_len_read)
);

encoding_fifo_w16_d8192_A outstream_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(lzw_compute_U0_outstream_din),
    .if_full_n(outstream_full_n),
    .if_write(lzw_compute_U0_outstream_write),
    .if_dout(outstream_dout),
    .if_empty_n(outstream_empty_n),
    .if_read(store_U0_outstream_read)
);

encoding_fifo_w32_d8192_A outlen_stream_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(lzw_compute_U0_outlen_stream_din),
    .if_full_n(outlen_stream_full_n),
    .if_write(lzw_compute_U0_outlen_stream_write),
    .if_dout(outlen_stream_dout),
    .if_empty_n(outlen_stream_empty_n),
    .if_read(store_U0_outlen_stream_read)
);

encoding_start_for_lzw_compute_U0 start_for_lzw_compute_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_lzw_compute_U0_din),
    .if_full_n(start_for_lzw_compute_U0_full_n),
    .if_write(load6_U0_start_write),
    .if_dout(start_for_lzw_compute_U0_dout),
    .if_empty_n(start_for_lzw_compute_U0_empty_n),
    .if_read(lzw_compute_U0_ap_ready)
);

encoding_start_for_store_U0 start_for_store_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_store_U0_din),
    .if_full_n(start_for_store_U0_full_n),
    .if_write(load6_U0_start_write),
    .if_dout(start_for_store_U0_dout),
    .if_empty_n(start_for_store_U0_empty_n),
    .if_read(store_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    ap_rst_n_inv <= ap_rst_reg_1;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_1 <= ap_rst_reg_2;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_2 <= ~ap_rst_n;
end

assign ap_done = store_U0_ap_done;

assign ap_idle = (store_U0_ap_idle & lzw_compute_U0_ap_idle & load6_U0_ap_idle);

assign ap_ready = load6_U0_ap_ready;

assign ap_sync_continue = ap_continue;

assign ap_sync_done = store_U0_ap_done;

assign ap_sync_ready = load6_U0_ap_ready;

assign load6_U0_ap_continue = 1'b1;

assign load6_U0_ap_start = ap_start;

assign load6_U0_start_full_n = (start_for_store_U0_full_n & start_for_lzw_compute_U0_full_n);

assign lzw_compute_U0_ap_continue = 1'b1;

assign lzw_compute_U0_ap_start = start_for_lzw_compute_U0_empty_n;

assign lzw_compute_U0_start_full_n = 1'b1;

assign lzw_compute_U0_start_write = 1'b0;

assign start_for_lzw_compute_U0_din = 1'b1;

assign start_for_store_U0_din = 1'b1;

assign store_U0_ap_continue = ap_continue;

assign store_U0_ap_start = start_for_store_U0_empty_n;

assign store_U0_start_full_n = 1'b1;

assign store_U0_start_write = 1'b0;

endmodule //encoding
