-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
-- Version: 2020.2
-- Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Filter_HW_stream is
generic (
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 6;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_P0_ADDR_WIDTH : INTEGER := 64;
    C_M_AXI_P0_ID_WIDTH : INTEGER := 1;
    C_M_AXI_P0_AWUSER_WIDTH : INTEGER := 1;
    C_M_AXI_P0_DATA_WIDTH : INTEGER := 512;
    C_M_AXI_P0_WUSER_WIDTH : INTEGER := 1;
    C_M_AXI_P0_ARUSER_WIDTH : INTEGER := 1;
    C_M_AXI_P0_RUSER_WIDTH : INTEGER := 1;
    C_M_AXI_P0_BUSER_WIDTH : INTEGER := 1;
    C_M_AXI_P1_ADDR_WIDTH : INTEGER := 64;
    C_M_AXI_P1_ID_WIDTH : INTEGER := 1;
    C_M_AXI_P1_AWUSER_WIDTH : INTEGER := 1;
    C_M_AXI_P1_DATA_WIDTH : INTEGER := 128;
    C_M_AXI_P1_WUSER_WIDTH : INTEGER := 1;
    C_M_AXI_P1_ARUSER_WIDTH : INTEGER := 1;
    C_M_AXI_P1_RUSER_WIDTH : INTEGER := 1;
    C_M_AXI_P1_BUSER_WIDTH : INTEGER := 1;
    C_M_AXI_P0_USER_VALUE : INTEGER := 0;
    C_M_AXI_P0_PROT_VALUE : INTEGER := 0;
    C_M_AXI_P0_CACHE_VALUE : INTEGER := 3;
    C_M_AXI_P1_USER_VALUE : INTEGER := 0;
    C_M_AXI_P1_PROT_VALUE : INTEGER := 0;
    C_M_AXI_P1_CACHE_VALUE : INTEGER := 3 );
port (
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    interrupt : OUT STD_LOGIC;
    m_axi_p0_AWVALID : OUT STD_LOGIC;
    m_axi_p0_AWREADY : IN STD_LOGIC;
    m_axi_p0_AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_P0_ADDR_WIDTH-1 downto 0);
    m_axi_p0_AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_P0_ID_WIDTH-1 downto 0);
    m_axi_p0_AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_p0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_p0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_p0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_p0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_p0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_p0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_p0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_p0_AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_P0_AWUSER_WIDTH-1 downto 0);
    m_axi_p0_WVALID : OUT STD_LOGIC;
    m_axi_p0_WREADY : IN STD_LOGIC;
    m_axi_p0_WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_P0_DATA_WIDTH-1 downto 0);
    m_axi_p0_WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_P0_DATA_WIDTH/8-1 downto 0);
    m_axi_p0_WLAST : OUT STD_LOGIC;
    m_axi_p0_WID : OUT STD_LOGIC_VECTOR (C_M_AXI_P0_ID_WIDTH-1 downto 0);
    m_axi_p0_WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_P0_WUSER_WIDTH-1 downto 0);
    m_axi_p0_ARVALID : OUT STD_LOGIC;
    m_axi_p0_ARREADY : IN STD_LOGIC;
    m_axi_p0_ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_P0_ADDR_WIDTH-1 downto 0);
    m_axi_p0_ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_P0_ID_WIDTH-1 downto 0);
    m_axi_p0_ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_p0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_p0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_p0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_p0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_p0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_p0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_p0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_p0_ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_P0_ARUSER_WIDTH-1 downto 0);
    m_axi_p0_RVALID : IN STD_LOGIC;
    m_axi_p0_RREADY : OUT STD_LOGIC;
    m_axi_p0_RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_P0_DATA_WIDTH-1 downto 0);
    m_axi_p0_RLAST : IN STD_LOGIC;
    m_axi_p0_RID : IN STD_LOGIC_VECTOR (C_M_AXI_P0_ID_WIDTH-1 downto 0);
    m_axi_p0_RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_P0_RUSER_WIDTH-1 downto 0);
    m_axi_p0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_p0_BVALID : IN STD_LOGIC;
    m_axi_p0_BREADY : OUT STD_LOGIC;
    m_axi_p0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_p0_BID : IN STD_LOGIC_VECTOR (C_M_AXI_P0_ID_WIDTH-1 downto 0);
    m_axi_p0_BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_P0_BUSER_WIDTH-1 downto 0);
    m_axi_p1_AWVALID : OUT STD_LOGIC;
    m_axi_p1_AWREADY : IN STD_LOGIC;
    m_axi_p1_AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_P1_ADDR_WIDTH-1 downto 0);
    m_axi_p1_AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_P1_ID_WIDTH-1 downto 0);
    m_axi_p1_AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_p1_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_p1_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_p1_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_p1_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_p1_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_p1_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_p1_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_p1_AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_P1_AWUSER_WIDTH-1 downto 0);
    m_axi_p1_WVALID : OUT STD_LOGIC;
    m_axi_p1_WREADY : IN STD_LOGIC;
    m_axi_p1_WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_P1_DATA_WIDTH-1 downto 0);
    m_axi_p1_WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_P1_DATA_WIDTH/8-1 downto 0);
    m_axi_p1_WLAST : OUT STD_LOGIC;
    m_axi_p1_WID : OUT STD_LOGIC_VECTOR (C_M_AXI_P1_ID_WIDTH-1 downto 0);
    m_axi_p1_WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_P1_WUSER_WIDTH-1 downto 0);
    m_axi_p1_ARVALID : OUT STD_LOGIC;
    m_axi_p1_ARREADY : IN STD_LOGIC;
    m_axi_p1_ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_P1_ADDR_WIDTH-1 downto 0);
    m_axi_p1_ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_P1_ID_WIDTH-1 downto 0);
    m_axi_p1_ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_p1_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_p1_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_p1_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_p1_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_p1_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_p1_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_p1_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_p1_ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_P1_ARUSER_WIDTH-1 downto 0);
    m_axi_p1_RVALID : IN STD_LOGIC;
    m_axi_p1_RREADY : OUT STD_LOGIC;
    m_axi_p1_RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_P1_DATA_WIDTH-1 downto 0);
    m_axi_p1_RLAST : IN STD_LOGIC;
    m_axi_p1_RID : IN STD_LOGIC_VECTOR (C_M_AXI_P1_ID_WIDTH-1 downto 0);
    m_axi_p1_RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_P1_RUSER_WIDTH-1 downto 0);
    m_axi_p1_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_p1_BVALID : IN STD_LOGIC;
    m_axi_p1_BREADY : OUT STD_LOGIC;
    m_axi_p1_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_p1_BID : IN STD_LOGIC_VECTOR (C_M_AXI_P1_ID_WIDTH-1 downto 0);
    m_axi_p1_BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_P1_BUSER_WIDTH-1 downto 0) );
end;


architecture behav of Filter_HW_stream is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "Filter_HW_stream_Filter_HW_stream,hls_ip_2020_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu3eg-sbva484-1-i,HLS_INPUT_CLOCK=6.670000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=4.869100,HLS_SYN_LAT=131025,HLS_SYN_TPT=130952,HLS_SYN_MEM=44,HLS_SYN_DSP=0,HLS_SYN_FF=5130,HLS_SYN_LUT=5384,HLS_VERSION=2020_2}";
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant C_S_AXI_WSTRB_WIDTH : INTEGER range 63 downto 0 := 4;
    constant C_S_AXI_ADDR_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant C_M_AXI_ID_WIDTH : INTEGER range 63 downto 0 := 1;
    constant C_M_AXI_ADDR_WIDTH : INTEGER range 63 downto 0 := 40;
    constant C_M_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant C_M_AXI_WSTRB_WIDTH : INTEGER range 63 downto 0 := 4;
    constant C_M_AXI_AWUSER_WIDTH : INTEGER range 63 downto 0 := 1;
    constant C_M_AXI_ARUSER_WIDTH : INTEGER range 63 downto 0 := 1;
    constant C_M_AXI_WUSER_WIDTH : INTEGER range 63 downto 0 := 1;
    constant C_M_AXI_RUSER_WIDTH : INTEGER range 63 downto 0 := 1;
    constant C_M_AXI_BUSER_WIDTH : INTEGER range 63 downto 0 := 1;
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv512_lc_1 : STD_LOGIC_VECTOR (511 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv512_lc_2 : STD_LOGIC_VECTOR (511 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv128_lc_1 : STD_LOGIC_VECTOR (127 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv128_lc_2 : STD_LOGIC_VECTOR (127 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal ap_rst_reg_2 : STD_LOGIC := '1';
attribute shreg_extract of ap_rst_reg_2 : signal is "no";
    signal ap_rst_reg_1 : STD_LOGIC := '1';
attribute shreg_extract of ap_rst_reg_1 : signal is "no";
    signal ap_rst_n_inv : STD_LOGIC := '1';
attribute shreg_extract of ap_rst_n_inv : signal is "no";
    signal Input_r : STD_LOGIC_VECTOR (63 downto 0);
    signal Output_r : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_start : STD_LOGIC;
    signal ap_ready : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_continue : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal p0_AWREADY : STD_LOGIC;
    signal p0_WREADY : STD_LOGIC;
    signal p0_ARREADY : STD_LOGIC;
    signal p0_RVALID : STD_LOGIC;
    signal p0_RDATA : STD_LOGIC_VECTOR (511 downto 0);
    signal p0_RLAST : STD_LOGIC;
    signal p0_RID : STD_LOGIC_VECTOR (0 downto 0);
    signal p0_RUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal p0_RRESP : STD_LOGIC_VECTOR (1 downto 0);
    signal p0_BVALID : STD_LOGIC;
    signal p0_BRESP : STD_LOGIC_VECTOR (1 downto 0);
    signal p0_BID : STD_LOGIC_VECTOR (0 downto 0);
    signal p0_BUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal p1_AWREADY : STD_LOGIC;
    signal p1_WREADY : STD_LOGIC;
    signal p1_ARREADY : STD_LOGIC;
    signal p1_RVALID : STD_LOGIC;
    signal p1_RDATA : STD_LOGIC_VECTOR (127 downto 0);
    signal p1_RLAST : STD_LOGIC;
    signal p1_RID : STD_LOGIC_VECTOR (0 downto 0);
    signal p1_RUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal p1_RRESP : STD_LOGIC_VECTOR (1 downto 0);
    signal p1_BVALID : STD_LOGIC;
    signal p1_BRESP : STD_LOGIC_VECTOR (1 downto 0);
    signal p1_BID : STD_LOGIC_VECTOR (0 downto 0);
    signal p1_BUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal Filter_HW_stream_entry3_U0_ap_start : STD_LOGIC;
    signal Filter_HW_stream_entry3_U0_ap_done : STD_LOGIC;
    signal Filter_HW_stream_entry3_U0_ap_continue : STD_LOGIC;
    signal Filter_HW_stream_entry3_U0_ap_idle : STD_LOGIC;
    signal Filter_HW_stream_entry3_U0_ap_ready : STD_LOGIC;
    signal Filter_HW_stream_entry3_U0_Input_out_din : STD_LOGIC_VECTOR (63 downto 0);
    signal Filter_HW_stream_entry3_U0_Input_out_write : STD_LOGIC;
    signal Filter_HW_stream_entry3_U0_Output_out_din : STD_LOGIC_VECTOR (63 downto 0);
    signal Filter_HW_stream_entry3_U0_Output_out_write : STD_LOGIC;
    signal load3_U0_ap_start : STD_LOGIC;
    signal load3_U0_start_full_n : STD_LOGIC;
    signal load3_U0_ap_done : STD_LOGIC;
    signal load3_U0_ap_continue : STD_LOGIC;
    signal load3_U0_ap_idle : STD_LOGIC;
    signal load3_U0_ap_ready : STD_LOGIC;
    signal load3_U0_start_out : STD_LOGIC;
    signal load3_U0_start_write : STD_LOGIC;
    signal load3_U0_m_axi_p0_AWVALID : STD_LOGIC;
    signal load3_U0_m_axi_p0_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal load3_U0_m_axi_p0_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal load3_U0_m_axi_p0_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal load3_U0_m_axi_p0_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal load3_U0_m_axi_p0_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal load3_U0_m_axi_p0_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal load3_U0_m_axi_p0_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal load3_U0_m_axi_p0_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal load3_U0_m_axi_p0_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal load3_U0_m_axi_p0_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal load3_U0_m_axi_p0_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal load3_U0_m_axi_p0_WVALID : STD_LOGIC;
    signal load3_U0_m_axi_p0_WDATA : STD_LOGIC_VECTOR (511 downto 0);
    signal load3_U0_m_axi_p0_WSTRB : STD_LOGIC_VECTOR (63 downto 0);
    signal load3_U0_m_axi_p0_WLAST : STD_LOGIC;
    signal load3_U0_m_axi_p0_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal load3_U0_m_axi_p0_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal load3_U0_m_axi_p0_ARVALID : STD_LOGIC;
    signal load3_U0_m_axi_p0_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal load3_U0_m_axi_p0_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal load3_U0_m_axi_p0_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal load3_U0_m_axi_p0_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal load3_U0_m_axi_p0_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal load3_U0_m_axi_p0_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal load3_U0_m_axi_p0_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal load3_U0_m_axi_p0_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal load3_U0_m_axi_p0_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal load3_U0_m_axi_p0_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal load3_U0_m_axi_p0_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal load3_U0_m_axi_p0_RREADY : STD_LOGIC;
    signal load3_U0_m_axi_p0_BREADY : STD_LOGIC;
    signal load3_U0_Input_r_read : STD_LOGIC;
    signal load3_U0_Output_r_read : STD_LOGIC;
    signal load3_U0_Output_out_din : STD_LOGIC_VECTOR (63 downto 0);
    signal load3_U0_Output_out_write : STD_LOGIC;
    signal load3_U0_input_stream_din : STD_LOGIC_VECTOR (7 downto 0);
    signal load3_U0_input_stream_write : STD_LOGIC;
    signal compute_U0_input_stream_read : STD_LOGIC;
    signal compute_U0_output_stream_din : STD_LOGIC_VECTOR (7 downto 0);
    signal compute_U0_output_stream_write : STD_LOGIC;
    signal compute_U0_ap_start : STD_LOGIC;
    signal compute_U0_ap_done : STD_LOGIC;
    signal compute_U0_ap_ready : STD_LOGIC;
    signal compute_U0_ap_idle : STD_LOGIC;
    signal compute_U0_ap_continue : STD_LOGIC;
    signal store_U0_ap_start : STD_LOGIC;
    signal store_U0_ap_done : STD_LOGIC;
    signal store_U0_ap_continue : STD_LOGIC;
    signal store_U0_ap_idle : STD_LOGIC;
    signal store_U0_ap_ready : STD_LOGIC;
    signal store_U0_m_axi_p1_AWVALID : STD_LOGIC;
    signal store_U0_m_axi_p1_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal store_U0_m_axi_p1_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal store_U0_m_axi_p1_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal store_U0_m_axi_p1_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal store_U0_m_axi_p1_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal store_U0_m_axi_p1_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal store_U0_m_axi_p1_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal store_U0_m_axi_p1_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal store_U0_m_axi_p1_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal store_U0_m_axi_p1_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal store_U0_m_axi_p1_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal store_U0_m_axi_p1_WVALID : STD_LOGIC;
    signal store_U0_m_axi_p1_WDATA : STD_LOGIC_VECTOR (127 downto 0);
    signal store_U0_m_axi_p1_WSTRB : STD_LOGIC_VECTOR (15 downto 0);
    signal store_U0_m_axi_p1_WLAST : STD_LOGIC;
    signal store_U0_m_axi_p1_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal store_U0_m_axi_p1_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal store_U0_m_axi_p1_ARVALID : STD_LOGIC;
    signal store_U0_m_axi_p1_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal store_U0_m_axi_p1_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal store_U0_m_axi_p1_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal store_U0_m_axi_p1_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal store_U0_m_axi_p1_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal store_U0_m_axi_p1_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal store_U0_m_axi_p1_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal store_U0_m_axi_p1_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal store_U0_m_axi_p1_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal store_U0_m_axi_p1_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal store_U0_m_axi_p1_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal store_U0_m_axi_p1_RREADY : STD_LOGIC;
    signal store_U0_m_axi_p1_BREADY : STD_LOGIC;
    signal store_U0_Output_r_read : STD_LOGIC;
    signal store_U0_output_stream_read : STD_LOGIC;
    signal ap_sync_continue : STD_LOGIC;
    signal Input_c_full_n : STD_LOGIC;
    signal Input_c_dout : STD_LOGIC_VECTOR (63 downto 0);
    signal Input_c_empty_n : STD_LOGIC;
    signal Output_c1_full_n : STD_LOGIC;
    signal Output_c1_dout : STD_LOGIC_VECTOR (63 downto 0);
    signal Output_c1_empty_n : STD_LOGIC;
    signal Output_c_full_n : STD_LOGIC;
    signal Output_c_dout : STD_LOGIC_VECTOR (63 downto 0);
    signal Output_c_empty_n : STD_LOGIC;
    signal input_stream_full_n : STD_LOGIC;
    signal input_stream_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal input_stream_empty_n : STD_LOGIC;
    signal output_stream_full_n : STD_LOGIC;
    signal output_stream_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal output_stream_empty_n : STD_LOGIC;
    signal ap_sync_done : STD_LOGIC;
    signal ap_sync_ready : STD_LOGIC;
    signal ap_sync_reg_Filter_HW_stream_entry3_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_Filter_HW_stream_entry3_U0_ap_ready : STD_LOGIC;
    signal ap_sync_reg_load3_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_load3_U0_ap_ready : STD_LOGIC;
    signal Filter_HW_stream_entry3_U0_start_full_n : STD_LOGIC;
    signal Filter_HW_stream_entry3_U0_start_write : STD_LOGIC;
    signal start_for_compute_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_compute_U0_full_n : STD_LOGIC;
    signal start_for_compute_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_compute_U0_empty_n : STD_LOGIC;
    signal start_for_store_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_store_U0_full_n : STD_LOGIC;
    signal start_for_store_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_store_U0_empty_n : STD_LOGIC;
    signal compute_U0_start_full_n : STD_LOGIC;
    signal compute_U0_start_write : STD_LOGIC;
    signal store_U0_start_full_n : STD_LOGIC;
    signal store_U0_start_write : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component Filter_HW_stream_Filter_HW_stream_entry3 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        Input_r : IN STD_LOGIC_VECTOR (63 downto 0);
        Output_r : IN STD_LOGIC_VECTOR (63 downto 0);
        Input_out_din : OUT STD_LOGIC_VECTOR (63 downto 0);
        Input_out_full_n : IN STD_LOGIC;
        Input_out_write : OUT STD_LOGIC;
        Output_out_din : OUT STD_LOGIC_VECTOR (63 downto 0);
        Output_out_full_n : IN STD_LOGIC;
        Output_out_write : OUT STD_LOGIC );
    end component;


    component Filter_HW_stream_load3 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        m_axi_p0_AWVALID : OUT STD_LOGIC;
        m_axi_p0_AWREADY : IN STD_LOGIC;
        m_axi_p0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_p0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_p0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_p0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_p0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_p0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_p0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_p0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_p0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_p0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_p0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_p0_WVALID : OUT STD_LOGIC;
        m_axi_p0_WREADY : IN STD_LOGIC;
        m_axi_p0_WDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
        m_axi_p0_WSTRB : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_p0_WLAST : OUT STD_LOGIC;
        m_axi_p0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_p0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_p0_ARVALID : OUT STD_LOGIC;
        m_axi_p0_ARREADY : IN STD_LOGIC;
        m_axi_p0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_p0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_p0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_p0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_p0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_p0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_p0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_p0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_p0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_p0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_p0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_p0_RVALID : IN STD_LOGIC;
        m_axi_p0_RREADY : OUT STD_LOGIC;
        m_axi_p0_RDATA : IN STD_LOGIC_VECTOR (511 downto 0);
        m_axi_p0_RLAST : IN STD_LOGIC;
        m_axi_p0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_p0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_p0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_p0_BVALID : IN STD_LOGIC;
        m_axi_p0_BREADY : OUT STD_LOGIC;
        m_axi_p0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_p0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_p0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        Input_r_dout : IN STD_LOGIC_VECTOR (63 downto 0);
        Input_r_empty_n : IN STD_LOGIC;
        Input_r_read : OUT STD_LOGIC;
        Output_r_dout : IN STD_LOGIC_VECTOR (63 downto 0);
        Output_r_empty_n : IN STD_LOGIC;
        Output_r_read : OUT STD_LOGIC;
        Output_out_din : OUT STD_LOGIC_VECTOR (63 downto 0);
        Output_out_full_n : IN STD_LOGIC;
        Output_out_write : OUT STD_LOGIC;
        input_stream_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        input_stream_full_n : IN STD_LOGIC;
        input_stream_write : OUT STD_LOGIC );
    end component;


    component Filter_HW_stream_compute IS
    port (
        input_stream_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        input_stream_empty_n : IN STD_LOGIC;
        input_stream_read : OUT STD_LOGIC;
        output_stream_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        output_stream_full_n : IN STD_LOGIC;
        output_stream_write : OUT STD_LOGIC;
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;


    component Filter_HW_stream_store IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        m_axi_p1_AWVALID : OUT STD_LOGIC;
        m_axi_p1_AWREADY : IN STD_LOGIC;
        m_axi_p1_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_p1_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_p1_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_p1_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_p1_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_p1_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_p1_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_p1_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_p1_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_p1_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_p1_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_p1_WVALID : OUT STD_LOGIC;
        m_axi_p1_WREADY : IN STD_LOGIC;
        m_axi_p1_WDATA : OUT STD_LOGIC_VECTOR (127 downto 0);
        m_axi_p1_WSTRB : OUT STD_LOGIC_VECTOR (15 downto 0);
        m_axi_p1_WLAST : OUT STD_LOGIC;
        m_axi_p1_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_p1_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_p1_ARVALID : OUT STD_LOGIC;
        m_axi_p1_ARREADY : IN STD_LOGIC;
        m_axi_p1_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_p1_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_p1_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_p1_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_p1_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_p1_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_p1_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_p1_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_p1_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_p1_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_p1_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_p1_RVALID : IN STD_LOGIC;
        m_axi_p1_RREADY : OUT STD_LOGIC;
        m_axi_p1_RDATA : IN STD_LOGIC_VECTOR (127 downto 0);
        m_axi_p1_RLAST : IN STD_LOGIC;
        m_axi_p1_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_p1_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_p1_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_p1_BVALID : IN STD_LOGIC;
        m_axi_p1_BREADY : OUT STD_LOGIC;
        m_axi_p1_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_p1_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_p1_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        Output_r_dout : IN STD_LOGIC_VECTOR (63 downto 0);
        Output_r_empty_n : IN STD_LOGIC;
        Output_r_read : OUT STD_LOGIC;
        output_stream_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        output_stream_empty_n : IN STD_LOGIC;
        output_stream_read : OUT STD_LOGIC );
    end component;


    component Filter_HW_stream_fifo_w64_d2_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (63 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (63 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component Filter_HW_stream_fifo_w64_d3_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (63 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (63 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component Filter_HW_stream_fifo_w8_d2_S_x IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (7 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (7 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component Filter_HW_stream_start_for_compute_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component Filter_HW_stream_start_for_store_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component Filter_HW_stream_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        Input_r : OUT STD_LOGIC_VECTOR (63 downto 0);
        Output_r : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_continue : OUT STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;


    component Filter_HW_stream_p0_m_axi IS
    generic (
        CONSERVATIVE : INTEGER;
        USER_DW : INTEGER;
        USER_AW : INTEGER;
        USER_MAXREQS : INTEGER;
        NUM_READ_OUTSTANDING : INTEGER;
        NUM_WRITE_OUTSTANDING : INTEGER;
        MAX_READ_BURST_LENGTH : INTEGER;
        MAX_WRITE_BURST_LENGTH : INTEGER;
        C_M_AXI_ID_WIDTH : INTEGER;
        C_M_AXI_ADDR_WIDTH : INTEGER;
        C_M_AXI_DATA_WIDTH : INTEGER;
        C_M_AXI_AWUSER_WIDTH : INTEGER;
        C_M_AXI_ARUSER_WIDTH : INTEGER;
        C_M_AXI_WUSER_WIDTH : INTEGER;
        C_M_AXI_RUSER_WIDTH : INTEGER;
        C_M_AXI_BUSER_WIDTH : INTEGER;
        C_USER_VALUE : INTEGER;
        C_PROT_VALUE : INTEGER;
        C_CACHE_VALUE : INTEGER );
    port (
        AWVALID : OUT STD_LOGIC;
        AWREADY : IN STD_LOGIC;
        AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_AWUSER_WIDTH-1 downto 0);
        WVALID : OUT STD_LOGIC;
        WREADY : IN STD_LOGIC;
        WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH/8-1 downto 0);
        WLAST : OUT STD_LOGIC;
        WID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_WUSER_WIDTH-1 downto 0);
        ARVALID : OUT STD_LOGIC;
        ARREADY : IN STD_LOGIC;
        ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_ARUSER_WIDTH-1 downto 0);
        RVALID : IN STD_LOGIC;
        RREADY : OUT STD_LOGIC;
        RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        RLAST : IN STD_LOGIC;
        RID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_RUSER_WIDTH-1 downto 0);
        RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BVALID : IN STD_LOGIC;
        BREADY : OUT STD_LOGIC;
        BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_BUSER_WIDTH-1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        I_ARVALID : IN STD_LOGIC;
        I_ARREADY : OUT STD_LOGIC;
        I_ARADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_ARID : IN STD_LOGIC_VECTOR (0 downto 0);
        I_ARLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_ARSIZE : IN STD_LOGIC_VECTOR (2 downto 0);
        I_ARLOCK : IN STD_LOGIC_VECTOR (1 downto 0);
        I_ARCACHE : IN STD_LOGIC_VECTOR (3 downto 0);
        I_ARQOS : IN STD_LOGIC_VECTOR (3 downto 0);
        I_ARPROT : IN STD_LOGIC_VECTOR (2 downto 0);
        I_ARUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        I_ARBURST : IN STD_LOGIC_VECTOR (1 downto 0);
        I_ARREGION : IN STD_LOGIC_VECTOR (3 downto 0);
        I_RVALID : OUT STD_LOGIC;
        I_RREADY : IN STD_LOGIC;
        I_RDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
        I_RID : OUT STD_LOGIC_VECTOR (0 downto 0);
        I_RUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        I_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        I_RLAST : OUT STD_LOGIC;
        I_AWVALID : IN STD_LOGIC;
        I_AWREADY : OUT STD_LOGIC;
        I_AWADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_AWID : IN STD_LOGIC_VECTOR (0 downto 0);
        I_AWLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_AWSIZE : IN STD_LOGIC_VECTOR (2 downto 0);
        I_AWLOCK : IN STD_LOGIC_VECTOR (1 downto 0);
        I_AWCACHE : IN STD_LOGIC_VECTOR (3 downto 0);
        I_AWQOS : IN STD_LOGIC_VECTOR (3 downto 0);
        I_AWPROT : IN STD_LOGIC_VECTOR (2 downto 0);
        I_AWUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        I_AWBURST : IN STD_LOGIC_VECTOR (1 downto 0);
        I_AWREGION : IN STD_LOGIC_VECTOR (3 downto 0);
        I_WVALID : IN STD_LOGIC;
        I_WREADY : OUT STD_LOGIC;
        I_WDATA : IN STD_LOGIC_VECTOR (511 downto 0);
        I_WID : IN STD_LOGIC_VECTOR (0 downto 0);
        I_WUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        I_WLAST : IN STD_LOGIC;
        I_WSTRB : IN STD_LOGIC_VECTOR (63 downto 0);
        I_BVALID : OUT STD_LOGIC;
        I_BREADY : IN STD_LOGIC;
        I_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        I_BID : OUT STD_LOGIC_VECTOR (0 downto 0);
        I_BUSER : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component Filter_HW_stream_p1_m_axi IS
    generic (
        CONSERVATIVE : INTEGER;
        USER_DW : INTEGER;
        USER_AW : INTEGER;
        USER_MAXREQS : INTEGER;
        NUM_READ_OUTSTANDING : INTEGER;
        NUM_WRITE_OUTSTANDING : INTEGER;
        MAX_READ_BURST_LENGTH : INTEGER;
        MAX_WRITE_BURST_LENGTH : INTEGER;
        C_M_AXI_ID_WIDTH : INTEGER;
        C_M_AXI_ADDR_WIDTH : INTEGER;
        C_M_AXI_DATA_WIDTH : INTEGER;
        C_M_AXI_AWUSER_WIDTH : INTEGER;
        C_M_AXI_ARUSER_WIDTH : INTEGER;
        C_M_AXI_WUSER_WIDTH : INTEGER;
        C_M_AXI_RUSER_WIDTH : INTEGER;
        C_M_AXI_BUSER_WIDTH : INTEGER;
        C_USER_VALUE : INTEGER;
        C_PROT_VALUE : INTEGER;
        C_CACHE_VALUE : INTEGER );
    port (
        AWVALID : OUT STD_LOGIC;
        AWREADY : IN STD_LOGIC;
        AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_AWUSER_WIDTH-1 downto 0);
        WVALID : OUT STD_LOGIC;
        WREADY : IN STD_LOGIC;
        WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH/8-1 downto 0);
        WLAST : OUT STD_LOGIC;
        WID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_WUSER_WIDTH-1 downto 0);
        ARVALID : OUT STD_LOGIC;
        ARREADY : IN STD_LOGIC;
        ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_ARUSER_WIDTH-1 downto 0);
        RVALID : IN STD_LOGIC;
        RREADY : OUT STD_LOGIC;
        RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        RLAST : IN STD_LOGIC;
        RID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_RUSER_WIDTH-1 downto 0);
        RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BVALID : IN STD_LOGIC;
        BREADY : OUT STD_LOGIC;
        BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_BUSER_WIDTH-1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        I_ARVALID : IN STD_LOGIC;
        I_ARREADY : OUT STD_LOGIC;
        I_ARADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_ARID : IN STD_LOGIC_VECTOR (0 downto 0);
        I_ARLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_ARSIZE : IN STD_LOGIC_VECTOR (2 downto 0);
        I_ARLOCK : IN STD_LOGIC_VECTOR (1 downto 0);
        I_ARCACHE : IN STD_LOGIC_VECTOR (3 downto 0);
        I_ARQOS : IN STD_LOGIC_VECTOR (3 downto 0);
        I_ARPROT : IN STD_LOGIC_VECTOR (2 downto 0);
        I_ARUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        I_ARBURST : IN STD_LOGIC_VECTOR (1 downto 0);
        I_ARREGION : IN STD_LOGIC_VECTOR (3 downto 0);
        I_RVALID : OUT STD_LOGIC;
        I_RREADY : IN STD_LOGIC;
        I_RDATA : OUT STD_LOGIC_VECTOR (127 downto 0);
        I_RID : OUT STD_LOGIC_VECTOR (0 downto 0);
        I_RUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        I_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        I_RLAST : OUT STD_LOGIC;
        I_AWVALID : IN STD_LOGIC;
        I_AWREADY : OUT STD_LOGIC;
        I_AWADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_AWID : IN STD_LOGIC_VECTOR (0 downto 0);
        I_AWLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_AWSIZE : IN STD_LOGIC_VECTOR (2 downto 0);
        I_AWLOCK : IN STD_LOGIC_VECTOR (1 downto 0);
        I_AWCACHE : IN STD_LOGIC_VECTOR (3 downto 0);
        I_AWQOS : IN STD_LOGIC_VECTOR (3 downto 0);
        I_AWPROT : IN STD_LOGIC_VECTOR (2 downto 0);
        I_AWUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        I_AWBURST : IN STD_LOGIC_VECTOR (1 downto 0);
        I_AWREGION : IN STD_LOGIC_VECTOR (3 downto 0);
        I_WVALID : IN STD_LOGIC;
        I_WREADY : OUT STD_LOGIC;
        I_WDATA : IN STD_LOGIC_VECTOR (127 downto 0);
        I_WID : IN STD_LOGIC_VECTOR (0 downto 0);
        I_WUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        I_WLAST : IN STD_LOGIC;
        I_WSTRB : IN STD_LOGIC_VECTOR (15 downto 0);
        I_BVALID : OUT STD_LOGIC;
        I_BREADY : IN STD_LOGIC;
        I_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        I_BID : OUT STD_LOGIC_VECTOR (0 downto 0);
        I_BUSER : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;



begin
    control_s_axi_U : component Filter_HW_stream_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        Input_r => Input_r,
        Output_r => Output_r,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_continue => ap_continue,
        ap_idle => ap_idle);

    p0_m_axi_U : component Filter_HW_stream_p0_m_axi
    generic map (
        CONSERVATIVE => 0,
        USER_DW => 512,
        USER_AW => 64,
        USER_MAXREQS => 69,
        NUM_READ_OUTSTANDING => 16,
        NUM_WRITE_OUTSTANDING => 16,
        MAX_READ_BURST_LENGTH => 16,
        MAX_WRITE_BURST_LENGTH => 16,
        C_M_AXI_ID_WIDTH => C_M_AXI_P0_ID_WIDTH,
        C_M_AXI_ADDR_WIDTH => C_M_AXI_P0_ADDR_WIDTH,
        C_M_AXI_DATA_WIDTH => C_M_AXI_P0_DATA_WIDTH,
        C_M_AXI_AWUSER_WIDTH => C_M_AXI_P0_AWUSER_WIDTH,
        C_M_AXI_ARUSER_WIDTH => C_M_AXI_P0_ARUSER_WIDTH,
        C_M_AXI_WUSER_WIDTH => C_M_AXI_P0_WUSER_WIDTH,
        C_M_AXI_RUSER_WIDTH => C_M_AXI_P0_RUSER_WIDTH,
        C_M_AXI_BUSER_WIDTH => C_M_AXI_P0_BUSER_WIDTH,
        C_USER_VALUE => C_M_AXI_P0_USER_VALUE,
        C_PROT_VALUE => C_M_AXI_P0_PROT_VALUE,
        C_CACHE_VALUE => C_M_AXI_P0_CACHE_VALUE)
    port map (
        AWVALID => m_axi_p0_AWVALID,
        AWREADY => m_axi_p0_AWREADY,
        AWADDR => m_axi_p0_AWADDR,
        AWID => m_axi_p0_AWID,
        AWLEN => m_axi_p0_AWLEN,
        AWSIZE => m_axi_p0_AWSIZE,
        AWBURST => m_axi_p0_AWBURST,
        AWLOCK => m_axi_p0_AWLOCK,
        AWCACHE => m_axi_p0_AWCACHE,
        AWPROT => m_axi_p0_AWPROT,
        AWQOS => m_axi_p0_AWQOS,
        AWREGION => m_axi_p0_AWREGION,
        AWUSER => m_axi_p0_AWUSER,
        WVALID => m_axi_p0_WVALID,
        WREADY => m_axi_p0_WREADY,
        WDATA => m_axi_p0_WDATA,
        WSTRB => m_axi_p0_WSTRB,
        WLAST => m_axi_p0_WLAST,
        WID => m_axi_p0_WID,
        WUSER => m_axi_p0_WUSER,
        ARVALID => m_axi_p0_ARVALID,
        ARREADY => m_axi_p0_ARREADY,
        ARADDR => m_axi_p0_ARADDR,
        ARID => m_axi_p0_ARID,
        ARLEN => m_axi_p0_ARLEN,
        ARSIZE => m_axi_p0_ARSIZE,
        ARBURST => m_axi_p0_ARBURST,
        ARLOCK => m_axi_p0_ARLOCK,
        ARCACHE => m_axi_p0_ARCACHE,
        ARPROT => m_axi_p0_ARPROT,
        ARQOS => m_axi_p0_ARQOS,
        ARREGION => m_axi_p0_ARREGION,
        ARUSER => m_axi_p0_ARUSER,
        RVALID => m_axi_p0_RVALID,
        RREADY => m_axi_p0_RREADY,
        RDATA => m_axi_p0_RDATA,
        RLAST => m_axi_p0_RLAST,
        RID => m_axi_p0_RID,
        RUSER => m_axi_p0_RUSER,
        RRESP => m_axi_p0_RRESP,
        BVALID => m_axi_p0_BVALID,
        BREADY => m_axi_p0_BREADY,
        BRESP => m_axi_p0_BRESP,
        BID => m_axi_p0_BID,
        BUSER => m_axi_p0_BUSER,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        I_ARVALID => load3_U0_m_axi_p0_ARVALID,
        I_ARREADY => p0_ARREADY,
        I_ARADDR => load3_U0_m_axi_p0_ARADDR,
        I_ARID => load3_U0_m_axi_p0_ARID,
        I_ARLEN => load3_U0_m_axi_p0_ARLEN,
        I_ARSIZE => load3_U0_m_axi_p0_ARSIZE,
        I_ARLOCK => load3_U0_m_axi_p0_ARLOCK,
        I_ARCACHE => load3_U0_m_axi_p0_ARCACHE,
        I_ARQOS => load3_U0_m_axi_p0_ARQOS,
        I_ARPROT => load3_U0_m_axi_p0_ARPROT,
        I_ARUSER => load3_U0_m_axi_p0_ARUSER,
        I_ARBURST => load3_U0_m_axi_p0_ARBURST,
        I_ARREGION => load3_U0_m_axi_p0_ARREGION,
        I_RVALID => p0_RVALID,
        I_RREADY => load3_U0_m_axi_p0_RREADY,
        I_RDATA => p0_RDATA,
        I_RID => p0_RID,
        I_RUSER => p0_RUSER,
        I_RRESP => p0_RRESP,
        I_RLAST => p0_RLAST,
        I_AWVALID => ap_const_logic_0,
        I_AWREADY => p0_AWREADY,
        I_AWADDR => ap_const_lv64_0,
        I_AWID => ap_const_lv1_0,
        I_AWLEN => ap_const_lv32_0,
        I_AWSIZE => ap_const_lv3_0,
        I_AWLOCK => ap_const_lv2_0,
        I_AWCACHE => ap_const_lv4_0,
        I_AWQOS => ap_const_lv4_0,
        I_AWPROT => ap_const_lv3_0,
        I_AWUSER => ap_const_lv1_0,
        I_AWBURST => ap_const_lv2_0,
        I_AWREGION => ap_const_lv4_0,
        I_WVALID => ap_const_logic_0,
        I_WREADY => p0_WREADY,
        I_WDATA => ap_const_lv512_lc_1,
        I_WID => ap_const_lv1_0,
        I_WUSER => ap_const_lv1_0,
        I_WLAST => ap_const_logic_0,
        I_WSTRB => ap_const_lv64_0,
        I_BVALID => p0_BVALID,
        I_BREADY => ap_const_logic_0,
        I_BRESP => p0_BRESP,
        I_BID => p0_BID,
        I_BUSER => p0_BUSER);

    p1_m_axi_U : component Filter_HW_stream_p1_m_axi
    generic map (
        CONSERVATIVE => 0,
        USER_DW => 128,
        USER_AW => 64,
        USER_MAXREQS => 69,
        NUM_READ_OUTSTANDING => 16,
        NUM_WRITE_OUTSTANDING => 16,
        MAX_READ_BURST_LENGTH => 16,
        MAX_WRITE_BURST_LENGTH => 16,
        C_M_AXI_ID_WIDTH => C_M_AXI_P1_ID_WIDTH,
        C_M_AXI_ADDR_WIDTH => C_M_AXI_P1_ADDR_WIDTH,
        C_M_AXI_DATA_WIDTH => C_M_AXI_P1_DATA_WIDTH,
        C_M_AXI_AWUSER_WIDTH => C_M_AXI_P1_AWUSER_WIDTH,
        C_M_AXI_ARUSER_WIDTH => C_M_AXI_P1_ARUSER_WIDTH,
        C_M_AXI_WUSER_WIDTH => C_M_AXI_P1_WUSER_WIDTH,
        C_M_AXI_RUSER_WIDTH => C_M_AXI_P1_RUSER_WIDTH,
        C_M_AXI_BUSER_WIDTH => C_M_AXI_P1_BUSER_WIDTH,
        C_USER_VALUE => C_M_AXI_P1_USER_VALUE,
        C_PROT_VALUE => C_M_AXI_P1_PROT_VALUE,
        C_CACHE_VALUE => C_M_AXI_P1_CACHE_VALUE)
    port map (
        AWVALID => m_axi_p1_AWVALID,
        AWREADY => m_axi_p1_AWREADY,
        AWADDR => m_axi_p1_AWADDR,
        AWID => m_axi_p1_AWID,
        AWLEN => m_axi_p1_AWLEN,
        AWSIZE => m_axi_p1_AWSIZE,
        AWBURST => m_axi_p1_AWBURST,
        AWLOCK => m_axi_p1_AWLOCK,
        AWCACHE => m_axi_p1_AWCACHE,
        AWPROT => m_axi_p1_AWPROT,
        AWQOS => m_axi_p1_AWQOS,
        AWREGION => m_axi_p1_AWREGION,
        AWUSER => m_axi_p1_AWUSER,
        WVALID => m_axi_p1_WVALID,
        WREADY => m_axi_p1_WREADY,
        WDATA => m_axi_p1_WDATA,
        WSTRB => m_axi_p1_WSTRB,
        WLAST => m_axi_p1_WLAST,
        WID => m_axi_p1_WID,
        WUSER => m_axi_p1_WUSER,
        ARVALID => m_axi_p1_ARVALID,
        ARREADY => m_axi_p1_ARREADY,
        ARADDR => m_axi_p1_ARADDR,
        ARID => m_axi_p1_ARID,
        ARLEN => m_axi_p1_ARLEN,
        ARSIZE => m_axi_p1_ARSIZE,
        ARBURST => m_axi_p1_ARBURST,
        ARLOCK => m_axi_p1_ARLOCK,
        ARCACHE => m_axi_p1_ARCACHE,
        ARPROT => m_axi_p1_ARPROT,
        ARQOS => m_axi_p1_ARQOS,
        ARREGION => m_axi_p1_ARREGION,
        ARUSER => m_axi_p1_ARUSER,
        RVALID => m_axi_p1_RVALID,
        RREADY => m_axi_p1_RREADY,
        RDATA => m_axi_p1_RDATA,
        RLAST => m_axi_p1_RLAST,
        RID => m_axi_p1_RID,
        RUSER => m_axi_p1_RUSER,
        RRESP => m_axi_p1_RRESP,
        BVALID => m_axi_p1_BVALID,
        BREADY => m_axi_p1_BREADY,
        BRESP => m_axi_p1_BRESP,
        BID => m_axi_p1_BID,
        BUSER => m_axi_p1_BUSER,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        I_ARVALID => ap_const_logic_0,
        I_ARREADY => p1_ARREADY,
        I_ARADDR => ap_const_lv64_0,
        I_ARID => ap_const_lv1_0,
        I_ARLEN => ap_const_lv32_0,
        I_ARSIZE => ap_const_lv3_0,
        I_ARLOCK => ap_const_lv2_0,
        I_ARCACHE => ap_const_lv4_0,
        I_ARQOS => ap_const_lv4_0,
        I_ARPROT => ap_const_lv3_0,
        I_ARUSER => ap_const_lv1_0,
        I_ARBURST => ap_const_lv2_0,
        I_ARREGION => ap_const_lv4_0,
        I_RVALID => p1_RVALID,
        I_RREADY => ap_const_logic_0,
        I_RDATA => p1_RDATA,
        I_RID => p1_RID,
        I_RUSER => p1_RUSER,
        I_RRESP => p1_RRESP,
        I_RLAST => p1_RLAST,
        I_AWVALID => store_U0_m_axi_p1_AWVALID,
        I_AWREADY => p1_AWREADY,
        I_AWADDR => store_U0_m_axi_p1_AWADDR,
        I_AWID => store_U0_m_axi_p1_AWID,
        I_AWLEN => store_U0_m_axi_p1_AWLEN,
        I_AWSIZE => store_U0_m_axi_p1_AWSIZE,
        I_AWLOCK => store_U0_m_axi_p1_AWLOCK,
        I_AWCACHE => store_U0_m_axi_p1_AWCACHE,
        I_AWQOS => store_U0_m_axi_p1_AWQOS,
        I_AWPROT => store_U0_m_axi_p1_AWPROT,
        I_AWUSER => store_U0_m_axi_p1_AWUSER,
        I_AWBURST => store_U0_m_axi_p1_AWBURST,
        I_AWREGION => store_U0_m_axi_p1_AWREGION,
        I_WVALID => store_U0_m_axi_p1_WVALID,
        I_WREADY => p1_WREADY,
        I_WDATA => store_U0_m_axi_p1_WDATA,
        I_WID => store_U0_m_axi_p1_WID,
        I_WUSER => store_U0_m_axi_p1_WUSER,
        I_WLAST => store_U0_m_axi_p1_WLAST,
        I_WSTRB => store_U0_m_axi_p1_WSTRB,
        I_BVALID => p1_BVALID,
        I_BREADY => store_U0_m_axi_p1_BREADY,
        I_BRESP => p1_BRESP,
        I_BID => p1_BID,
        I_BUSER => p1_BUSER);

    Filter_HW_stream_entry3_U0 : component Filter_HW_stream_Filter_HW_stream_entry3
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => Filter_HW_stream_entry3_U0_ap_start,
        ap_done => Filter_HW_stream_entry3_U0_ap_done,
        ap_continue => Filter_HW_stream_entry3_U0_ap_continue,
        ap_idle => Filter_HW_stream_entry3_U0_ap_idle,
        ap_ready => Filter_HW_stream_entry3_U0_ap_ready,
        Input_r => Input_r,
        Output_r => Output_r,
        Input_out_din => Filter_HW_stream_entry3_U0_Input_out_din,
        Input_out_full_n => Input_c_full_n,
        Input_out_write => Filter_HW_stream_entry3_U0_Input_out_write,
        Output_out_din => Filter_HW_stream_entry3_U0_Output_out_din,
        Output_out_full_n => Output_c1_full_n,
        Output_out_write => Filter_HW_stream_entry3_U0_Output_out_write);

    load3_U0 : component Filter_HW_stream_load3
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => load3_U0_ap_start,
        start_full_n => load3_U0_start_full_n,
        ap_done => load3_U0_ap_done,
        ap_continue => load3_U0_ap_continue,
        ap_idle => load3_U0_ap_idle,
        ap_ready => load3_U0_ap_ready,
        start_out => load3_U0_start_out,
        start_write => load3_U0_start_write,
        m_axi_p0_AWVALID => load3_U0_m_axi_p0_AWVALID,
        m_axi_p0_AWREADY => ap_const_logic_0,
        m_axi_p0_AWADDR => load3_U0_m_axi_p0_AWADDR,
        m_axi_p0_AWID => load3_U0_m_axi_p0_AWID,
        m_axi_p0_AWLEN => load3_U0_m_axi_p0_AWLEN,
        m_axi_p0_AWSIZE => load3_U0_m_axi_p0_AWSIZE,
        m_axi_p0_AWBURST => load3_U0_m_axi_p0_AWBURST,
        m_axi_p0_AWLOCK => load3_U0_m_axi_p0_AWLOCK,
        m_axi_p0_AWCACHE => load3_U0_m_axi_p0_AWCACHE,
        m_axi_p0_AWPROT => load3_U0_m_axi_p0_AWPROT,
        m_axi_p0_AWQOS => load3_U0_m_axi_p0_AWQOS,
        m_axi_p0_AWREGION => load3_U0_m_axi_p0_AWREGION,
        m_axi_p0_AWUSER => load3_U0_m_axi_p0_AWUSER,
        m_axi_p0_WVALID => load3_U0_m_axi_p0_WVALID,
        m_axi_p0_WREADY => ap_const_logic_0,
        m_axi_p0_WDATA => load3_U0_m_axi_p0_WDATA,
        m_axi_p0_WSTRB => load3_U0_m_axi_p0_WSTRB,
        m_axi_p0_WLAST => load3_U0_m_axi_p0_WLAST,
        m_axi_p0_WID => load3_U0_m_axi_p0_WID,
        m_axi_p0_WUSER => load3_U0_m_axi_p0_WUSER,
        m_axi_p0_ARVALID => load3_U0_m_axi_p0_ARVALID,
        m_axi_p0_ARREADY => p0_ARREADY,
        m_axi_p0_ARADDR => load3_U0_m_axi_p0_ARADDR,
        m_axi_p0_ARID => load3_U0_m_axi_p0_ARID,
        m_axi_p0_ARLEN => load3_U0_m_axi_p0_ARLEN,
        m_axi_p0_ARSIZE => load3_U0_m_axi_p0_ARSIZE,
        m_axi_p0_ARBURST => load3_U0_m_axi_p0_ARBURST,
        m_axi_p0_ARLOCK => load3_U0_m_axi_p0_ARLOCK,
        m_axi_p0_ARCACHE => load3_U0_m_axi_p0_ARCACHE,
        m_axi_p0_ARPROT => load3_U0_m_axi_p0_ARPROT,
        m_axi_p0_ARQOS => load3_U0_m_axi_p0_ARQOS,
        m_axi_p0_ARREGION => load3_U0_m_axi_p0_ARREGION,
        m_axi_p0_ARUSER => load3_U0_m_axi_p0_ARUSER,
        m_axi_p0_RVALID => p0_RVALID,
        m_axi_p0_RREADY => load3_U0_m_axi_p0_RREADY,
        m_axi_p0_RDATA => p0_RDATA,
        m_axi_p0_RLAST => p0_RLAST,
        m_axi_p0_RID => p0_RID,
        m_axi_p0_RUSER => p0_RUSER,
        m_axi_p0_RRESP => p0_RRESP,
        m_axi_p0_BVALID => ap_const_logic_0,
        m_axi_p0_BREADY => load3_U0_m_axi_p0_BREADY,
        m_axi_p0_BRESP => ap_const_lv2_0,
        m_axi_p0_BID => ap_const_lv1_0,
        m_axi_p0_BUSER => ap_const_lv1_0,
        Input_r_dout => Input_c_dout,
        Input_r_empty_n => Input_c_empty_n,
        Input_r_read => load3_U0_Input_r_read,
        Output_r_dout => Output_c1_dout,
        Output_r_empty_n => Output_c1_empty_n,
        Output_r_read => load3_U0_Output_r_read,
        Output_out_din => load3_U0_Output_out_din,
        Output_out_full_n => Output_c_full_n,
        Output_out_write => load3_U0_Output_out_write,
        input_stream_din => load3_U0_input_stream_din,
        input_stream_full_n => input_stream_full_n,
        input_stream_write => load3_U0_input_stream_write);

    compute_U0 : component Filter_HW_stream_compute
    port map (
        input_stream_dout => input_stream_dout,
        input_stream_empty_n => input_stream_empty_n,
        input_stream_read => compute_U0_input_stream_read,
        output_stream_din => compute_U0_output_stream_din,
        output_stream_full_n => output_stream_full_n,
        output_stream_write => compute_U0_output_stream_write,
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => compute_U0_ap_start,
        ap_done => compute_U0_ap_done,
        ap_ready => compute_U0_ap_ready,
        ap_idle => compute_U0_ap_idle,
        ap_continue => compute_U0_ap_continue);

    store_U0 : component Filter_HW_stream_store
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => store_U0_ap_start,
        ap_done => store_U0_ap_done,
        ap_continue => store_U0_ap_continue,
        ap_idle => store_U0_ap_idle,
        ap_ready => store_U0_ap_ready,
        m_axi_p1_AWVALID => store_U0_m_axi_p1_AWVALID,
        m_axi_p1_AWREADY => p1_AWREADY,
        m_axi_p1_AWADDR => store_U0_m_axi_p1_AWADDR,
        m_axi_p1_AWID => store_U0_m_axi_p1_AWID,
        m_axi_p1_AWLEN => store_U0_m_axi_p1_AWLEN,
        m_axi_p1_AWSIZE => store_U0_m_axi_p1_AWSIZE,
        m_axi_p1_AWBURST => store_U0_m_axi_p1_AWBURST,
        m_axi_p1_AWLOCK => store_U0_m_axi_p1_AWLOCK,
        m_axi_p1_AWCACHE => store_U0_m_axi_p1_AWCACHE,
        m_axi_p1_AWPROT => store_U0_m_axi_p1_AWPROT,
        m_axi_p1_AWQOS => store_U0_m_axi_p1_AWQOS,
        m_axi_p1_AWREGION => store_U0_m_axi_p1_AWREGION,
        m_axi_p1_AWUSER => store_U0_m_axi_p1_AWUSER,
        m_axi_p1_WVALID => store_U0_m_axi_p1_WVALID,
        m_axi_p1_WREADY => p1_WREADY,
        m_axi_p1_WDATA => store_U0_m_axi_p1_WDATA,
        m_axi_p1_WSTRB => store_U0_m_axi_p1_WSTRB,
        m_axi_p1_WLAST => store_U0_m_axi_p1_WLAST,
        m_axi_p1_WID => store_U0_m_axi_p1_WID,
        m_axi_p1_WUSER => store_U0_m_axi_p1_WUSER,
        m_axi_p1_ARVALID => store_U0_m_axi_p1_ARVALID,
        m_axi_p1_ARREADY => ap_const_logic_0,
        m_axi_p1_ARADDR => store_U0_m_axi_p1_ARADDR,
        m_axi_p1_ARID => store_U0_m_axi_p1_ARID,
        m_axi_p1_ARLEN => store_U0_m_axi_p1_ARLEN,
        m_axi_p1_ARSIZE => store_U0_m_axi_p1_ARSIZE,
        m_axi_p1_ARBURST => store_U0_m_axi_p1_ARBURST,
        m_axi_p1_ARLOCK => store_U0_m_axi_p1_ARLOCK,
        m_axi_p1_ARCACHE => store_U0_m_axi_p1_ARCACHE,
        m_axi_p1_ARPROT => store_U0_m_axi_p1_ARPROT,
        m_axi_p1_ARQOS => store_U0_m_axi_p1_ARQOS,
        m_axi_p1_ARREGION => store_U0_m_axi_p1_ARREGION,
        m_axi_p1_ARUSER => store_U0_m_axi_p1_ARUSER,
        m_axi_p1_RVALID => ap_const_logic_0,
        m_axi_p1_RREADY => store_U0_m_axi_p1_RREADY,
        m_axi_p1_RDATA => ap_const_lv128_lc_1,
        m_axi_p1_RLAST => ap_const_logic_0,
        m_axi_p1_RID => ap_const_lv1_0,
        m_axi_p1_RUSER => ap_const_lv1_0,
        m_axi_p1_RRESP => ap_const_lv2_0,
        m_axi_p1_BVALID => p1_BVALID,
        m_axi_p1_BREADY => store_U0_m_axi_p1_BREADY,
        m_axi_p1_BRESP => p1_BRESP,
        m_axi_p1_BID => p1_BID,
        m_axi_p1_BUSER => p1_BUSER,
        Output_r_dout => Output_c_dout,
        Output_r_empty_n => Output_c_empty_n,
        Output_r_read => store_U0_Output_r_read,
        output_stream_dout => output_stream_dout,
        output_stream_empty_n => output_stream_empty_n,
        output_stream_read => store_U0_output_stream_read);

    Input_c_U : component Filter_HW_stream_fifo_w64_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Filter_HW_stream_entry3_U0_Input_out_din,
        if_full_n => Input_c_full_n,
        if_write => Filter_HW_stream_entry3_U0_Input_out_write,
        if_dout => Input_c_dout,
        if_empty_n => Input_c_empty_n,
        if_read => load3_U0_Input_r_read);

    Output_c1_U : component Filter_HW_stream_fifo_w64_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Filter_HW_stream_entry3_U0_Output_out_din,
        if_full_n => Output_c1_full_n,
        if_write => Filter_HW_stream_entry3_U0_Output_out_write,
        if_dout => Output_c1_dout,
        if_empty_n => Output_c1_empty_n,
        if_read => load3_U0_Output_r_read);

    Output_c_U : component Filter_HW_stream_fifo_w64_d3_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => load3_U0_Output_out_din,
        if_full_n => Output_c_full_n,
        if_write => load3_U0_Output_out_write,
        if_dout => Output_c_dout,
        if_empty_n => Output_c_empty_n,
        if_read => store_U0_Output_r_read);

    input_stream_U : component Filter_HW_stream_fifo_w8_d2_S_x
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => load3_U0_input_stream_din,
        if_full_n => input_stream_full_n,
        if_write => load3_U0_input_stream_write,
        if_dout => input_stream_dout,
        if_empty_n => input_stream_empty_n,
        if_read => compute_U0_input_stream_read);

    output_stream_U : component Filter_HW_stream_fifo_w8_d2_S_x
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => compute_U0_output_stream_din,
        if_full_n => output_stream_full_n,
        if_write => compute_U0_output_stream_write,
        if_dout => output_stream_dout,
        if_empty_n => output_stream_empty_n,
        if_read => store_U0_output_stream_read);

    start_for_compute_U0_U : component Filter_HW_stream_start_for_compute_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_compute_U0_din,
        if_full_n => start_for_compute_U0_full_n,
        if_write => load3_U0_start_write,
        if_dout => start_for_compute_U0_dout,
        if_empty_n => start_for_compute_U0_empty_n,
        if_read => compute_U0_ap_ready);

    start_for_store_U0_U : component Filter_HW_stream_start_for_store_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_store_U0_din,
        if_full_n => start_for_store_U0_full_n,
        if_write => load3_U0_start_write,
        if_dout => start_for_store_U0_dout,
        if_empty_n => start_for_store_U0_empty_n,
        if_read => store_U0_ap_ready);





    ap_sync_reg_Filter_HW_stream_entry3_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_Filter_HW_stream_entry3_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_Filter_HW_stream_entry3_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_Filter_HW_stream_entry3_U0_ap_ready <= ap_sync_Filter_HW_stream_entry3_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_load3_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_load3_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_load3_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_load3_U0_ap_ready <= ap_sync_load3_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    ap_rst_n_inv_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_rst_n_inv <= ap_rst_reg_1;
        end if;
    end process;

    ap_rst_reg_1_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_rst_reg_1 <= ap_rst_reg_2;
        end if;
    end process;

    ap_rst_reg_2_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
                        ap_rst_reg_2 <= not(ap_rst_n);
        end if;
    end process;
    Filter_HW_stream_entry3_U0_ap_continue <= ap_const_logic_1;
    Filter_HW_stream_entry3_U0_ap_start <= ((ap_sync_reg_Filter_HW_stream_entry3_U0_ap_ready xor ap_const_logic_1) and ap_start);
    Filter_HW_stream_entry3_U0_start_full_n <= ap_const_logic_1;
    Filter_HW_stream_entry3_U0_start_write <= ap_const_logic_0;
    ap_done <= store_U0_ap_done;
    ap_idle <= (store_U0_ap_idle and load3_U0_ap_idle and compute_U0_ap_idle and Filter_HW_stream_entry3_U0_ap_idle);
    ap_ready <= ap_sync_ready;
    ap_sync_Filter_HW_stream_entry3_U0_ap_ready <= (ap_sync_reg_Filter_HW_stream_entry3_U0_ap_ready or Filter_HW_stream_entry3_U0_ap_ready);
    ap_sync_continue <= ap_continue;
    ap_sync_done <= store_U0_ap_done;
    ap_sync_load3_U0_ap_ready <= (load3_U0_ap_ready or ap_sync_reg_load3_U0_ap_ready);
    ap_sync_ready <= (ap_sync_load3_U0_ap_ready and ap_sync_Filter_HW_stream_entry3_U0_ap_ready);
    compute_U0_ap_continue <= ap_const_logic_1;
    compute_U0_ap_start <= start_for_compute_U0_empty_n;
    compute_U0_start_full_n <= ap_const_logic_1;
    compute_U0_start_write <= ap_const_logic_0;
    load3_U0_ap_continue <= ap_const_logic_1;
    load3_U0_ap_start <= ((ap_sync_reg_load3_U0_ap_ready xor ap_const_logic_1) and ap_start);
    load3_U0_start_full_n <= (start_for_store_U0_full_n and start_for_compute_U0_full_n);
    start_for_compute_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_store_U0_din <= (0=>ap_const_logic_1, others=>'-');
    store_U0_ap_continue <= ap_continue;
    store_U0_ap_start <= start_for_store_U0_empty_n;
    store_U0_start_full_n <= ap_const_logic_1;
    store_U0_start_write <= ap_const_logic_0;
end behav;
